'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');

const { stripInert, stripInertJs, findEmDashes, walk } = require('../scripts/emDashDensity');

function mkTmpDir(prefix) {
  return fs.mkdtempSync(path.join(os.tmpdir(), prefix));
}

function writeFile(dir, relPath, content) {
  const full = path.join(dir, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content, 'utf8');
  return full;
}

test('findEmDashes catches both the literal character and the &mdash; entity', () => {
  assert.deepEqual(findEmDashes('a plain — dash'), ['a plain — dash']);
  assert.deepEqual(findEmDashes('an entity &mdash; dash'), ['an entity &mdash; dash']);
  assert.deepEqual(findEmDashes('nothing here, just a hyphen - fine'), []);
});

test('stripInert removes HTML comments, <style>, and <script> contents', () => {
  const html = '<!-- — --><style>.x{content:"—"}</style><p>real — copy</p><script>var x="—";</script>';
  const visible = stripInert(html);
  const hits = findEmDashes(visible);
  assert.equal(hits.length, 1);
  assert.match(hits[0], /real — copy/);
});

test('stripInertJs removes block comments but leaves string literals intact', () => {
  const js = '/* a — comment, never shipped as copy */ var msg = "real — copy";';
  const visible = stripInertJs(js);
  const hits = findEmDashes(visible);
  assert.equal(hits.length, 1);
  assert.match(hits[0], /real — copy/);
});

test('stripInertJs deliberately does not touch // line comments (unsafe on minified single-line bundles)', () => {
  // Simulates a minifyWhitespace-collapsed bundle: a URL containing "//"
  // followed on the same "line" by a real copy string. A naive
  // line-comment stripper would delete the copy string below along with
  // the URL; stripInertJs must not do that.
  const js = 'var href="https://example.com/x";var msg="real — copy";';
  const visible = stripInertJs(js);
  const hits = findEmDashes(visible);
  assert.equal(hits.length, 1);
  assert.match(hits[0], /real — copy/);
});

test('walk() includes .html, .xml, and .js files, and skips other extensions', () => {
  const dir = mkTmpDir('emdash-walk-');
  try {
    writeFile(dir, 'index.html', '<p>hi</p>');
    writeFile(dir, 'sitemap.xml', '<urlset></urlset>');
    writeFile(dir, 'repertoire-builder.js', 'var x = 1;');
    writeFile(dir, 'notes.txt', 'ignore me');
    writeFile(dir, 'sub/nested.html', '<p>nested</p>');

    const found = walk(dir).map((p) => path.relative(dir, p)).sort();
    assert.deepEqual(found, [
      'index.html',
      'repertoire-builder.js',
      'sitemap.xml',
      path.join('sub', 'nested.html'),
    ].sort());
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('a runtime-generated em dash in a client-JS bundle is detected end to end', () => {
  const dir = mkTmpDir('emdash-js-');
  try {
    // Mirrors how a *.client.js bundle assigns copy at runtime.
    writeFile(
      dir,
      'drill-hub.js',
      '/* Auto-generated by src/buildStatic.js (esbuild) */\n' +
        'el.textContent = "3 correct — keep going";'
    );
    const files = walk(dir);
    assert.equal(files.length, 1);
    const raw = fs.readFileSync(files[0], 'utf8');
    const hits = findEmDashes(stripInertJs(raw));
    assert.equal(hits.length, 1);
    assert.match(hits[0], /correct — keep going/);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});
