/* Auto-generated by src/buildStatic.js from src/chessPosition.js,
 * src/drillLogic.js, and src/browser/drill.client.js. Do not edit this
 * file directly -- edit the source files above and re-run `node
 * src/buildStatic.js`.
 *
 * This makes no network requests -- every position/percentage it uses
 * comes from the #drill-data JSON block already on the page. */


'use strict';

/**
 * Minimal board-state tracker for rendering static position diagrams from a
 * UCI move list. NO legal-move generation and NO check detection -- every
 * move list this project plays comes straight from the Lichess Opening
 * Explorer API and is legal by construction (spec section 3.9). This module
 * only needs to know where the pieces physically end up after normal moves,
 * castling, en passant, and promotion.
 *
 * Board representation: a plain object keyed by algebraic square ('e4') to
 * a single FEN piece letter (uppercase = white, lowercase = black), or no
 * key at all for an empty square. Every function here is pure -- it returns
 * a new board object rather than mutating its input.
 */

const FILES = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'];
const RANKS = ['1', '2', '3', '4', '5', '6', '7', '8'];

const START_BOARD = {
  a1: 'R', b1: 'N', c1: 'B', d1: 'Q', e1: 'K', f1: 'B', g1: 'N', h1: 'R',
  a2: 'P', b2: 'P', c2: 'P', d2: 'P', e2: 'P', f2: 'P', g2: 'P', h2: 'P',
  a7: 'p', b7: 'p', c7: 'p', d7: 'p', e7: 'p', f7: 'p', g7: 'p', h7: 'p',
  a8: 'r', b8: 'n', c8: 'b', d8: 'q', e8: 'k', f8: 'b', g8: 'n', h8: 'r',
};

/**
 * Applies one UCI move ("e2e4", "e7e8q", ...) to a board, returning a new
 * board. Handles the three special cases a legal-by-construction move list
 * still needs: castling (king moves two files -> move the rook too), en
 * passant (pawn captures diagonally onto an empty square -> remove the
 * captured pawn), and promotion (5th UCI character replaces the piece).
 */
function applyUciMove(board, uci) {
  if (typeof uci !== 'string' || uci.length < 4) {
    throw new Error(`applyUciMove: invalid uci "${uci}"`);
  }
  const from = uci.slice(0, 2);
  const to = uci.slice(2, 4);
  const promo = uci.length > 4 ? uci[4] : null;
  const piece = board[from];
  if (!piece) {
    throw new Error(`applyUciMove: no piece on ${from} for move "${uci}"`);
  }

  const next = { ...board };
  delete next[from];

  const isWhite = piece === piece.toUpperCase();
  const isPawn = piece.toUpperCase() === 'P';
  const isKing = piece.toUpperCase() === 'K';

  // En passant: a pawn moving diagonally onto a square with nothing on it
  // must be capturing the pawn that just passed it, which sits on the
  // departure rank / arrival file.
  if (isPawn && from[0] !== to[0] && !board[to]) {
    delete next[`${to[0]}${from[1]}`];
  }

  // Castling: king moves exactly two files -> move the matching rook too.
  if (isKing && Math.abs(FILES.indexOf(to[0]) - FILES.indexOf(from[0])) === 2) {
    const rank = from[1];
    if (to[0] === 'g') {
      next[`f${rank}`] = next[`h${rank}`];
      delete next[`h${rank}`];
    } else if (to[0] === 'c') {
      next[`d${rank}`] = next[`a${rank}`];
      delete next[`a${rank}`];
    }
  }

  next[to] = promo ? (isWhite ? promo.toUpperCase() : promo.toLowerCase()) : piece;
  return next;
}

function applyUciMoves(board, ucis) {
  return ucis.reduce((b, uci) => applyUciMove(b, uci), board);
}



'use strict';

/**
 * Pure grading and progression logic for the opening drill (beta pilot).
 * No DOM, no I/O, no network -- everything here takes plain data in and
 * returns plain data out, same convention as process.js and
 * processRepertoire.js. This is also bundled straight into the browser (see
 * buildStatic.js's browser-bundle helper), which is why it has to stay pure
 * and keep the trailing module.exports block below intact.
 *
 * Every move in a drill's baked tree (see buildDrill.js) comes from the
 * Lichess Opening Explorer and is legal by construction. This module never
 * validates a move's legality -- it only ever matches a played move against
 * a known-good set of candidates for the current position.
 */

/**
 * Normalizes free-text move input for comparison: lowercased, with
 * whitespace and check/annotation punctuation (+ # ! ?) stripped. Works the
 * same whether the input is UCI ("f1c4") or SAN ("Bc4+!").
 *
 * @param {string} str
 * @returns {string}
 */
function normalizeMoveInput(str) {
  if (typeof str !== 'string') return '';
  return str.toLowerCase().replace(/[\s+#!?]/g, '');
}

/**
 * Grades one user move against a drill userNode.
 *
 * @param {object} opts
 * @param {{candidates: object[], answerUci: string}} opts.node
 * @param {string} opts.input raw move text (UCI or SAN, any case)
 * @returns {{verdict: 'correct'|'offmeta'|'unknown', played: object|null, answer: object}}
 */
function gradeMove({ node, input }) {
  if (!node || !Array.isArray(node.candidates) || node.candidates.length === 0) {
    throw new Error('gradeMove: node.candidates must be a non-empty array');
  }
  const answer = node.candidates[0];
  const normalizedInput = normalizeMoveInput(input);

  let played = null;
  for (const candidate of node.candidates) {
    if (normalizedInput === normalizeMoveInput(candidate.uci) || normalizedInput === normalizeMoveInput(candidate.san)) {
      played = candidate;
      break;
    }
  }

  let verdict;
  if (!played) {
    verdict = 'unknown';
  } else if (played.uci === node.answerUci) {
    verdict = 'correct';
  } else {
    verdict = 'offmeta';
  }

  return { verdict, played, answer };
}

/**
 * Picks one reply from an oppNode's replies list, weighted by playedPct
 * (falling back to equal weight for any reply with no usable playedPct).
 * `rand` is injected (a number in [0, 1)) instead of read from Math.random
 * internally, so callers can get deterministic output for tests.
 *
 * @param {object[]} replies
 * @param {number} [rand]
 * @returns {object} one member of `replies`
 */
function pickReply(replies, rand = Math.random()) {
  if (!Array.isArray(replies) || replies.length === 0) {
    throw new Error('pickReply: replies must be a non-empty array');
  }
  const weights = replies.map((reply) => (typeof reply.playedPct === 'number' && reply.playedPct > 0 ? reply.playedPct : 1));
  const total = weights.reduce((sum, w) => sum + w, 0);

  let threshold = rand * total;
  for (let i = 0; i < replies.length; i += 1) {
    threshold -= weights[i];
    if (threshold < 0) {
      return replies[i];
    }
  }
  return replies[replies.length - 1];
}

/**
 * Applies the outcome of one drill round to the user's saved progress.
 * Three clean rounds in a row at the current level unlock the next level
 * (capped at 4); anything else resets the clean streak but never demotes --
 * this is a beta practice pilot, not a ranked ladder.
 *
 * @param {{level:number, cleanStreak:number}} state
 * @param {{clean:boolean}} outcome
 * @returns {{level:number, cleanStreak:number}}
 */
function applyRoundResult(state, { clean }) {
  const level = state && typeof state.level === 'number' ? state.level : 1;
  const cleanStreak = state && typeof state.cleanStreak === 'number' ? state.cleanStreak : 0;

  if (!clean) {
    return { level, cleanStreak: 0 };
  }

  const nextStreak = cleanStreak + 1;
  if (nextStreak >= 3) {
    return { level: Math.min(level + 1, 4), cleanStreak: 0 };
  }
  return { level, cleanStreak: nextStreak };
}


'use strict';

/**
 * Page controller for the static opening-drill page (dist/italian-game-drill.html).
 *
 * This file is NOT loaded via CommonJS module loading -- it's appended as
 * plain text after src/chessPosition.js and src/drillLogic.js by
 * src/buildStatic.js's buildDrillBundle(), so it runs in the same top-level
 * scope and can call applyUciMove / applyUciMoves / START_BOARD / FILES /
 * RANKS (chessPosition.js) and normalizeMoveInput / gradeMove / pickReply /
 * applyRoundResult (drillLogic.js) directly, without any import statement.
 * All non-DOM logic lives in those two bundled modules; this file only
 * paints the board, wires up events, and reads/writes localStorage.
 *
 * Every move in the baked drill tree comes from the Lichess Opening
 * Explorer and is legal by construction (see chessPosition.js's own header
 * comment) -- this controller never validates a move's legality itself.
 *
 * Wrapped in an IIFE only to keep its own helper names out of the shared
 * top-level scope the bundled modules above it use.
 */
(function () {
  var STORAGE_KEY = 'lichess-stats.drill.italian-game.v1';
  var PIECE_NAMES = { k: 'king', q: 'queen', r: 'rook', b: 'bishop', n: 'knight', p: 'pawn' };

  var dataEl = document.getElementById('drill-data');
  if (!dataEl) return; // no drill data present -- nothing to wire up

  var drillData;
  try {
    drillData = JSON.parse(dataEl.textContent);
  } catch (err) {
    return; // corrupt data -- leave the server-rendered page as-is
  }

  var boardRoot = document.querySelector('[data-drill-board]');
  var form = document.getElementById('drill-move-form');
  var input = document.getElementById('drill-move-text');
  var showAnswerBtn = document.getElementById('drill-show-answer');
  var bandSelect = document.getElementById('drill-band');
  var levelSelect = document.getElementById('drill-level');
  var feedbackEl = document.getElementById('drill-feedback');
  var announceEl = document.getElementById('drill-announce');
  var candidateTableEl = document.getElementById('drill-candidate-table');
  var progressEl = document.getElementById('drill-level-progress');
  if (!boardRoot || !form || !input || !bandSelect || !levelSelect) return;

  function loadState() {
    try {
      var raw = window.localStorage.getItem(STORAGE_KEY);
      if (!raw) throw new Error('none saved yet');
      var parsed = JSON.parse(raw);
      if (typeof parsed.level !== 'number' || typeof parsed.cleanStreak !== 'number' || typeof parsed.band !== 'string') {
        throw new Error('unexpected shape');
      }
      if (!drillData.bands[parsed.band]) throw new Error('unknown band');
      return parsed;
    } catch (err) {
      var fallbackBand = Object.prototype.hasOwnProperty.call(drillData.bands, '1600-1800')
        ? '1600-1800'
        : Object.keys(drillData.bands)[0];
      return { level: 1, cleanStreak: 0, band: fallbackBand };
    }
  }

  function saveState(state) {
    try {
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    } catch (err) {
      // localStorage unavailable (private mode, quota, disabled) -- the
      // drill still works for this page load, it just won't remember
      // progress on reload.
    }
  }

  var state = loadState();
  var round = null; // {board, oppNode, userNode, level, band, movesDone, clean, selected}

  function squareButtons() {
    return boardRoot.querySelectorAll('.board-sq');
  }

  function pieceLabel(piece) {
    if (!piece) return null;
    var isWhite = piece === piece.toUpperCase();
    return (isWhite ? 'white ' : 'black ') + (PIECE_NAMES[piece.toLowerCase()] || '');
  }

  function paintBoard(board) {
    var buttons = squareButtons();
    for (var i = 0; i < buttons.length; i += 1) {
      var btn = buttons[i];
      var sq = btn.getAttribute('data-square');
      var piece = board[sq];
      var isWhite = !!piece && piece === piece.toUpperCase();
      var glyph = piece ? drillData.glyphs[piece.toLowerCase()] : '';
      btn.innerHTML = glyph ? '<span class="board-pc--' + (isWhite ? 'w' : 'b') + '" aria-hidden="true">' + glyph + '</span>' : '';
      var label = pieceLabel(piece) ? sq + ', ' + pieceLabel(piece) : sq + ', empty';
      btn.setAttribute('aria-label', label);
      btn.setAttribute('aria-pressed', 'false');
    }
  }

  function announce(text) {
    if (announceEl) announceEl.textContent = text;
  }

  function setFeedback(verdict, text) {
    if (!feedbackEl) return;
    feedbackEl.className = verdict ? 'drill-feedback drill-feedback--' + verdict : 'drill-feedback';
    feedbackEl.textContent = text;
  }

  function renderCandidateTable(candidates) {
    if (!candidateTableEl) return;
    var rows = candidates
      .map(function (c) {
        return '<tr><td>' + c.san + '</td><td>' + (c.playedPct != null ? c.playedPct + '%' : '-') + '</td><td>' +
          (c.winPct != null ? c.winPct + '%' : '-') + '</td><td>' + c.games.toLocaleString() + '</td></tr>';
      })
      .join('');
    candidateTableEl.innerHTML = '<table><thead><tr><th scope="col">Move</th><th scope="col">Pick %</th><th scope="col">Score %</th><th scope="col">Games</th></tr></thead><tbody>' + rows + '</tbody></table>';
  }

  function applyMoveToBoard(uci) {
    round.board = applyUciMove(round.board, uci);
    paintBoard(round.board);
  }

  function isWhitePiece(piece) {
    return !!piece && piece === piece.toUpperCase();
  }

  function updateProgress() {
    if (!progressEl) return;
    var moveInRound = round ? round.movesDone + 1 : 1;
    progressEl.textContent = 'Level ' + state.level + ', move ' + Math.min(moveInRound, state.level) + ' of ' + state.level +
      '. Clean streak: ' + state.cleanStreak + '/3.';
  }

  function updateLevelOptions() {
    var options = levelSelect.options;
    for (var i = 0; i < options.length; i += 1) {
      var lvl = Number(options[i].value);
      options[i].disabled = lvl > state.level;
      options[i].textContent = 'Level ' + lvl + (lvl > state.level ? ' (locked)' : '');
    }
    levelSelect.value = String(state.level);
  }

  function clearSelection() {
    var buttons = squareButtons();
    for (var i = 0; i < buttons.length; i += 1) {
      buttons[i].setAttribute('aria-pressed', 'false');
    }
  }

  function playOpponentPly() {
    var reply = pickReply(round.oppNode.replies, Math.random());
    applyMoveToBoard(reply.uci);
    round.userNode = reply.node;
    announce(
      'The opponent plays ' + reply.san +
        (reply.playedPct != null ? ' -- ' + reply.playedPct + '% of players at ' + round.band + ' play this here.' : '.')
    );
    renderCandidateTable(round.userNode.candidates);
    updateProgress();
  }

  function startRound() {
    round = {
      board: applyUciMoves(START_BOARD, drillData.prefix.map(function (p) { return p.uci; })),
      oppNode: drillData.bands[state.band],
      userNode: null,
      level: state.level,
      band: state.band,
      movesDone: 0,
      clean: true,
      selected: null,
    };
    paintBoard(round.board);
    setFeedback('', '');
    playOpponentPly();
  }

  function finishRound() {
    var next = applyRoundResult({ level: state.level, cleanStreak: state.cleanStreak }, { clean: round.clean });
    var leveledUp = next.level > state.level;
    state.level = next.level;
    state.cleanStreak = next.cleanStreak;
    saveState(state);
    updateLevelOptions();
    announce(
      (round.clean ? 'Round complete, clean. ' : 'Round complete. ') +
        (leveledUp ? 'Level ' + state.level + ' unlocked!' : '')
    );
    round = null;
    updateProgress();
  }

  function gradeAndAdvance(rawInput, usedShowAnswer) {
    if (!round || !round.userNode) return;
    var result = gradeMove({ node: round.userNode, input: rawInput });
    var answer = result.answer;

    if (usedShowAnswer) {
      round.clean = false;
      setFeedback('unknown', 'The move is ' + answer.san + ' -- ' + answer.playedPct + '% of players at ' + round.band + ' play this here, scoring ' + answer.winPct + '% for White.');
    } else if (result.verdict === 'correct') {
      setFeedback('correct', answer.san + ' -- correct. ' + answer.playedPct + '% of ' + round.band + ' players play this here, and it scores ' + answer.winPct + '% for White (n = ' + answer.games.toLocaleString() + ').');
    } else if (result.verdict === 'offmeta') {
      round.clean = false;
      setFeedback('offmeta', result.played.san + ' -- a real move, but off-meta here. ' + result.played.playedPct + '% of ' + round.band + ' players choose it and it scores ' + result.played.winPct + '% for White. The band-typical move is ' + answer.san + ': ' + answer.playedPct + '% pick rate, ' + answer.winPct + '% score.');
    } else {
      round.clean = false;
      setFeedback('unknown', 'That is not a move players make in this position at ' + round.band + '. The band-typical move is ' + answer.san + ' -- ' + answer.playedPct + '% pick rate, ' + answer.winPct + '% score.');
    }

    // Only the top candidate's line continues into the baked tree, so every
    // round advances via the answer move regardless of what was typed --
    // the user still sees exactly what they played graded against it above.
    applyMoveToBoard(answer.uci);
    round.movesDone += 1;

    if (round.movesDone >= round.level || !round.userNode.then) {
      finishRound();
      return;
    }
    round.userNode = null;
    playOpponentPly();
  }

  function handleSquareClick(square) {
    if (!round || !round.userNode) return;
    var piece = round.board[square];
    if (round.selected == null) {
      if (!isWhitePiece(piece)) {
        announce('No white piece on ' + square + '.');
        return;
      }
      round.selected = square;
      clearSelection();
      var btn = boardRoot.querySelector('[data-square="' + square + '"]');
      if (btn) btn.setAttribute('aria-pressed', 'true');
      return;
    }
    if (round.selected === square) {
      round.selected = null;
      clearSelection();
      return;
    }
    var from = round.selected;
    round.selected = null;
    clearSelection();
    gradeAndAdvance(from + square, false);
  }

  boardRoot.addEventListener('click', function (event) {
    var target = event.target;
    while (target && target !== boardRoot && !target.classList.contains('board-sq')) {
      target = target.parentNode;
    }
    if (!target || target === boardRoot) return;
    handleSquareClick(target.getAttribute('data-square'));
  });

  form.addEventListener('submit', function (event) {
    event.preventDefault();
    var value = input.value.trim();
    if (!value) return;
    input.value = '';
    gradeAndAdvance(value, false);
  });

  if (showAnswerBtn) {
    showAnswerBtn.addEventListener('click', function () {
      if (!round || !round.userNode) return;
      gradeAndAdvance(round.userNode.answerUci, true);
    });
  }

  bandSelect.addEventListener('change', function () {
    state.band = bandSelect.value;
    saveState(state);
    startRound();
  });

  levelSelect.addEventListener('change', function () {
    var lvl = Number(levelSelect.value);
    if (lvl > state.level) {
      levelSelect.value = String(state.level);
      return;
    }
    state.level = lvl;
    saveState(state);
    startRound();
  });

  bandSelect.value = state.band;
  updateLevelOptions();
  startRound();
})();
