/* Auto-generated by src/buildStatic.js from src/fetchLichess.js, src/process.js,
 * src/render.js, and src/browser/playerLookup.client.js. Do not edit this file
 * directly -- edit the source files above and re-run `node src/buildStatic.js`.
 *
 * This calls only Lichess's keyless public API (https://lichess.org/api)
 * directly from your browser. No Lichess API token is used, read, or present
 * anywhere in this file. */


'use strict';

/**
 * Data-fetch module for the Lichess public API (https://lichess.org/api).
 * No API key is required for the endpoints used here.
 *
 * Every exported function accepts an options object with an injectable
 * `fetchImpl` (defaulting to the global `fetch`) specifically so tests can
 * supply a fake implementation backed by fixture JSON instead of hitting
 * the live network.
 */

const BASE_URL = 'https://lichess.org';

class LichessNotFoundError extends Error {
  constructor(username) {
    super(`Lichess user not found: ${username}`);
    this.name = 'LichessNotFoundError';
    this.username = username;
  }
}

class LichessRateLimitError extends Error {
  constructor(retryAfter) {
    super(`Lichess API rate limit hit${retryAfter ? ` (retry after ${retryAfter}s)` : ''}`);
    this.name = 'LichessRateLimitError';
    this.retryAfter = retryAfter || null;
  }
}

class LichessApiError extends Error {
  constructor(status, statusText, url) {
    super(`Lichess API request failed: ${status} ${statusText} (${url})`);
    this.name = 'LichessApiError';
    this.status = status;
  }
}

/**
 * Shared response handling: maps HTTP status codes to typed errors.
 */
async function handleErrors(response, url, username) {
  if (response.status === 404) {
    throw new LichessNotFoundError(username);
  }
  if (response.status === 429) {
    const retryAfter = response.headers && typeof response.headers.get === 'function'
      ? response.headers.get('retry-after')
      : null;
    throw new LichessRateLimitError(retryAfter);
  }
  if (!response.ok) {
    throw new LichessApiError(response.status, response.statusText, url);
  }
}

/**
 * GET /api/user/:username -> profile JSON (includes perfs, counts, etc).
 */
async function fetchUserProfile(username, { fetchImpl = fetch } = {}) {
  const url = `${BASE_URL}/api/user/${encodeURIComponent(username)}`;
  const response = await fetchImpl(url, { headers: { Accept: 'application/json' } });
  await handleErrors(response, url, username);
  return response.json();
}

/**
 * GET /api/user/:username/rating-history -> array of
 * { name: <variant>, points: [[year, month0Indexed, day, rating], ...] }
 */
async function fetchRatingHistory(username, { fetchImpl = fetch } = {}) {
  const url = `${BASE_URL}/api/user/${encodeURIComponent(username)}/rating-history`;
  const response = await fetchImpl(url, { headers: { Accept: 'application/json' } });
  await handleErrors(response, url, username);
  return response.json();
}

/**
 * GET /api/games/user/:username -> newline-delimited JSON (one game per line)
 * when Accept: application/x-ndjson is sent.
 */
async function fetchRecentGames(username, { max = 10, fetchImpl = fetch } = {}) {
  const url = `${BASE_URL}/api/games/user/${encodeURIComponent(username)}?max=${encodeURIComponent(max)}&moves=false`;
  const response = await fetchImpl(url, { headers: { Accept: 'application/x-ndjson' } });
  await handleErrors(response, url, username);
  const text = await response.text();
  return text
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => JSON.parse(line));
}


'use strict';

/**
 * Pure processing/aggregation functions. No I/O here at all -- everything
 * takes plain data in and returns plain data out, which is what makes these
 * unit-testable against static fixture JSON.
 */

/**
 * Summarize a rating-history payload (as returned by
 * fetchLichess.fetchRatingHistory) into one row per variant with the stats
 * a stats page would actually want to show.
 *
 * @param {Array<{name: string, points: Array<[number, number, number, number]>}>} history
 * @returns {Array<{variant: string, current: number|null, peak: number|null,
 *   low: number|null, gamesRecorded: number, firstDate: string|null,
 *   lastDate: string|null, change: number|null}>}
 */
function summarizeRatingHistory(history) {
  if (!Array.isArray(history)) return [];

  return history
    .map((variant) => {
      const points = Array.isArray(variant.points) ? variant.points : [];
      if (points.length === 0) {
        return {
          variant: variant.name,
          current: null,
          peak: null,
          low: null,
          gamesRecorded: 0,
          firstDate: null,
          lastDate: null,
          change: null,
        };
      }

      const ratings = points.map((p) => p[3]);
      const first = points[0];
      const last = points[points.length - 1];

      return {
        variant: variant.name,
        current: last[3],
        peak: Math.max(...ratings),
        low: Math.min(...ratings),
        gamesRecorded: points.length,
        firstDate: pointToDateString(first),
        lastDate: pointToDateString(last),
        change: last[3] - first[3],
      };
    })
    // Drop variants Lichess reports with zero history points -- nothing to show.
    .filter((row) => row.gamesRecorded > 0);
}

function pointToDateString([year, month0, day]) {
  // Lichess months are 0-indexed (0 = January).
  const mm = String(month0 + 1).padStart(2, '0');
  const dd = String(day).padStart(2, '0');
  return `${year}-${mm}-${dd}`;
}

/**
 * Summarize a list of recent games (as returned by
 * fetchLichess.fetchRecentGames) relative to a given username: win/loss/draw
 * counts, win rate, average opponent rating, and a flat per-game result list
 * ready for rendering.
 *
 * @param {Array<object>} games
 * @param {string} username
 * @returns {{totalGames: number, wins: number, losses: number, draws: number,
 *   winRate: number|null, avgOpponentRating: number|null,
 *   results: Array<{opponent: string, opponentRating: number|null,
 *     result: 'win'|'loss'|'draw', color: 'white'|'black', variant: string,
 *     speed: string, date: string|null}>}}
 */
function summarizeGames(games, username) {
  if (!Array.isArray(games) || !username) {
    return { totalGames: 0, wins: 0, losses: 0, draws: 0, winRate: null, avgOpponentRating: null, results: [] };
  }

  const lowerUsername = username.toLowerCase();
  let wins = 0;
  let losses = 0;
  let draws = 0;
  let opponentRatingSum = 0;
  let opponentRatingCount = 0;

  const results = games.map((game) => {
    const players = game.players || {};
    const white = players.white || {};
    const black = players.black || {};
    const whiteName = ((white.user && white.user.name) || 'anonymous').toLowerCase();
    const isWhite = whiteName === lowerUsername;
    const me = isWhite ? white : black;
    const opponent = isWhite ? black : white;

    let result;
    if (!game.winner) {
      result = 'draw';
      draws += 1;
    } else if (game.winner === (isWhite ? 'white' : 'black')) {
      result = 'win';
      wins += 1;
    } else {
      result = 'loss';
      losses += 1;
    }

    const opponentRating = typeof opponent.rating === 'number' ? opponent.rating : null;
    if (opponentRating !== null) {
      opponentRatingSum += opponentRating;
      opponentRatingCount += 1;
    }

    return {
      opponent: (opponent.user && opponent.user.name) || 'Anonymous',
      opponentRating,
      result,
      color: isWhite ? 'white' : 'black',
      variant: game.variant || 'standard',
      speed: game.speed || 'unknown',
      date: game.createdAt ? new Date(game.createdAt).toISOString().slice(0, 10) : null,
    };
  });

  const totalGames = games.length;
  return {
    totalGames,
    wins,
    losses,
    draws,
    winRate: totalGames > 0 ? Number(((wins / totalGames) * 100).toFixed(1)) : null,
    avgOpponentRating: opponentRatingCount > 0 ? Math.round(opponentRatingSum / opponentRatingCount) : null,
    results,
  };
}


'use strict';

/**
 * Rendering layer: a pure function that turns already-processed data into an
 * HTML string. No framework, no templating engine -- just template
 * literals. Kept separate from build.js/server.js so it can be reused by
 * both the static generator and the local dev server.
 */

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function renderRatingTable(ratingRows) {
  if (ratingRows.length === 0) {
    return '<p>No rating history found.</p>';
  }
  const rows = ratingRows
    .map(
      (row) => `
      <tr>
        <td>${escapeHtml(row.variant)}</td>
        <td>${row.current ?? '-'}</td>
        <td>${row.peak ?? '-'}</td>
        <td>${row.low ?? '-'}</td>
        <td>${row.change >= 0 ? '+' : ''}${row.change ?? '-'}</td>
        <td>${row.gamesRecorded}</td>
      </tr>`
    )
    .join('');

  return `
    <table>
      <thead>
        <tr><th>Variant</th><th>Current</th><th>Peak</th><th>Low</th><th>Change</th><th>Data points</th></tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>`;
}

function renderGamesTable(gameSummary) {
  if (gameSummary.totalGames === 0) {
    return '<p>No recent games found.</p>';
  }
  const rows = gameSummary.results
    .map(
      (r) => `
      <tr class="result-${r.result}">
        <td>${r.date || '-'}</td>
        <td>${escapeHtml(r.opponent)}</td>
        <td>${r.opponentRating ?? '-'}</td>
        <td>${escapeHtml(r.color)}</td>
        <td>${escapeHtml(r.variant)} / ${escapeHtml(r.speed)}</td>
        <td>${escapeHtml(r.result)}</td>
      </tr>`
    )
    .join('');

  return `
    <p>${gameSummary.wins}W / ${gameSummary.losses}L / ${gameSummary.draws}D
       out of ${gameSummary.totalGames} games (win rate ${gameSummary.winRate}%,
       avg opponent rating ${gameSummary.avgOpponentRating ?? 'n/a'})</p>
    <table>
      <thead>
        <tr><th>Date</th><th>Opponent</th><th>Opp. rating</th><th>Color</th><th>Variant/Speed</th><th>Result</th></tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>`;
}

/**
 * @param {{username: string, ratingRows: Array, gameSummary: object}} data
 * @returns {string} a full standalone HTML document
 */
function renderPlayerPage({ username, ratingRows, gameSummary }) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>${escapeHtml(username)} - Lichess stats (proof of concept)</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 760px; margin: 2rem auto; padding: 0 1rem; color: #222; }
    h1 { margin-bottom: 0; }
    .subtitle { color: #666; margin-top: 0.25rem; }
    table { border-collapse: collapse; width: 100%; margin: 1rem 0 2rem; }
    th, td { text-align: left; padding: 0.4rem 0.6rem; border-bottom: 1px solid #ddd; }
    th { background: #f5f5f5; }
    tr.result-win { background: #eafaf0; }
    tr.result-loss { background: #fdecec; }
    tr.result-draw { background: #fafafa; }
    footer { color: #999; font-size: 0.8rem; margin-top: 3rem; }
  </style>
</head>
<body>
  <h1>${escapeHtml(username)}</h1>
  <p class="subtitle">Lichess rating history and recent games (engineering pipeline proof of concept)</p>

  <h2>Ratings by variant</h2>
  ${renderRatingTable(ratingRows)}

  <h2>Recent games</h2>
  ${renderGamesTable(gameSummary)}

  <footer>Data source: <a href="https://lichess.org/api">lichess.org/api</a>. Generated locally; not deployed or published.</footer>
</body>
</html>
`;
}

function renderRepertoireNode(node) {
  const winPct = node.winPct ?? '-';
  const drawPct = node.drawPct ?? '-';
  const lossPct = node.lossPct ?? '-';
  const ratingNote = node.averageRating ? ` &middot; avg rating ${node.averageRating}` : '';
  const children = node.children && node.children.length > 0
    ? `<ul>${node.children.map(renderRepertoireNode).join('')}</ul>`
    : '';

  return `
    <li>
      <span class="move move-${escapeHtml(node.mover)}">${escapeHtml(node.san)}</span>
      <span class="stats">${node.games.toLocaleString()} games (${node.playedPct ?? '-'}% of this position)
        &middot; ${node.mover} W/D/L: ${winPct}% / ${drawPct}% / ${lossPct}%${ratingNote}</span>
      ${children}
    </li>`;
}

function renderRepertoireTree(tree) {
  if (!Array.isArray(tree) || tree.length === 0) {
    return '<p>No repertoire data found for this rating band and color.</p>';
  }
  return `<ul class="repertoire-tree">${tree.map(renderRepertoireNode).join('')}</ul>`;
}

/**
 * @param {{ratingBand: string, color: string, opening: {eco:string,name:string}|null,
 *   totals: {white:number,draws:number,black:number}|null, tree: Array,
 *   nav?: {player: string, repertoire: string}}} data `nav` lets callers point
 *   the top-of-page links at either the dynamic dev-server routes (the
 *   default, used by server.js) or flat static filenames (used by the
 *   static build, e.g. {player: 'player.html', repertoire: 'index.html'}).
 * @returns {string} a full standalone HTML document
 */
function renderRepertoirePage({ ratingBand, color, opening, totals, tree, nav = { player: '/', repertoire: '/repertoire' } }) {
  const totalGames = totals ? totals.white + totals.draws + totals.black : null;
  const openingNote = opening ? ` &mdash; starting from ${escapeHtml(opening.name)} (${escapeHtml(opening.eco)})` : '';
  const totalsNote = totals
    ? `<p>${totalGames.toLocaleString()} games played from the starting position in this rating band
        (${totals.white.toLocaleString()}W / ${totals.draws.toLocaleString()}D / ${totals.black.toLocaleString()}L).</p>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Opening repertoire explorer (${escapeHtml(ratingBand)}, ${escapeHtml(color)}) - Lichess stats POC</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 820px; margin: 2rem auto; padding: 0 1rem; color: #222; }
    nav { margin-bottom: 1.5rem; }
    nav a { margin-right: 1rem; }
    h1 { margin-bottom: 0; }
    .subtitle { color: #666; margin-top: 0.25rem; }
    ul.repertoire-tree, ul.repertoire-tree ul { list-style: none; padding-left: 1.25rem; border-left: 2px solid #eee; }
    ul.repertoire-tree { padding-left: 0; border-left: none; }
    li { margin: 0.6rem 0; }
    .move { font-weight: 600; margin-right: 0.5rem; }
    .move-white { color: #234; }
    .move-black { color: #555; font-style: italic; }
    .stats { color: #666; font-size: 0.85rem; }
    footer { color: #999; font-size: 0.8rem; margin-top: 3rem; }
  </style>
</head>
<body>
  <nav><a href="${escapeHtml(nav.player)}">Player lookup</a><a href="${escapeHtml(nav.repertoire)}">Repertoire explorer</a></nav>
  <h1>Opening repertoire explorer</h1>
  <p class="subtitle">Rating band ${escapeHtml(ratingBand)}, playing as ${escapeHtml(color)}${openingNote}</p>
  ${totalsNote}
  <p>Most-played moves at each ply for players in this rating band, with win/draw/loss rates per move.
     Your color's plies show the top choices actually played at this rating; the opponent's replies show
     only their single most common response, to keep the tree readable.</p>
  ${renderRepertoireTree(tree)}
  <footer>Data source: <a href="https://lichess.org/api#tag/Opening-Explorer">Lichess Opening Explorer API</a>
    (explorer.lichess.ovh, keyless, no account required). Generated locally; not deployed or published.</footer>
</body>
</html>
`;
}


'use strict';

/**
 * Page controller for the static player-lookup page (dist/player.html).
 *
 * This file is NOT loaded via CommonJS module loading -- it's appended as plain text
 * after fetchLichess.js, process.js, and render.js by
 * buildStatic.js's buildPlayerLookupBundle(), so it runs in the same
 * top-level scope and can call fetchRatingHistory / fetchRecentGames /
 * summarizeRatingHistory / summarizeGames / renderRatingTable /
 * renderGamesTable / escapeHtml / LichessNotFoundError / LichessRateLimitError
 * / LichessApiError directly, without any import statement.
 *
 * It calls Lichess's already-public, keyless general API
 * (https://lichess.org/api) directly from the visitor's browser. No Lichess
 * API token is used, read, or referenced anywhere in this file.
 *
 * Wrapped in an IIFE only to keep its own helper names (lookupPlayer, $,
 * etc.) out of the shared top-level scope the bundled modules above it use;
 * it still reads their declarations via normal closure/script-scope lookup.
 */
(function () {
  function $(selector) {
    return document.querySelector(selector);
  }

  function setStatus(html) {
    $('#result').innerHTML = html;
  }

  async function lookupPlayer(username) {
    setStatus('<p>Loading…</p>');
    try {
      const [history, games] = await Promise.all([
        fetchRatingHistory(username),
        fetchRecentGames(username, { max: 15 }),
      ]);
      const ratingRows = summarizeRatingHistory(history);
      const gameSummary = summarizeGames(games, username);
      setStatus(`
        <h2>${escapeHtml(username)}</h2>
        <h3>Ratings by variant</h3>
        ${renderRatingTable(ratingRows)}
        <h3>Recent games</h3>
        ${renderGamesTable(gameSummary)}
      `);
    } catch (err) {
      if (err instanceof LichessNotFoundError) {
        setStatus(`<p class="error">No such Lichess user: ${escapeHtml(username)}</p>`);
      } else if (err instanceof LichessRateLimitError) {
        setStatus('<p class="error">Lichess API rate limit hit, try again shortly.</p>');
      } else if (err instanceof LichessApiError) {
        setStatus(`<p class="error">Lichess API request failed: ${escapeHtml(err.message)}</p>`);
      } else if (err instanceof TypeError) {
        // A raw fetch()/network failure (offline, CORS block, etc) surfaces
        // as a TypeError with no useful HTTP status attached.
        setStatus(`<p class="error">Could not reach the Lichess API from this page (network error or the browser blocked the cross-origin request). Details: ${escapeHtml(err.message)}</p>`);
      } else {
        setStatus(`<p class="error">Lookup failed: ${escapeHtml(err.message)}</p>`);
      }
    }
  }

  function init() {
    const form = $('#lookup-form');
    if (!form) return;
    form.addEventListener('submit', (event) => {
      event.preventDefault();
      const username = $('#username').value.trim();
      if (!username) return;
      const url = new URL(window.location.href);
      url.searchParams.set('username', username);
      window.history.replaceState(null, '', url);
      lookupPlayer(username);
    });

    const params = new URLSearchParams(window.location.search);
    const prefill = params.get('username');
    if (prefill) {
      $('#username').value = prefill;
      lookupPlayer(prefill);
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
