/* Auto-generated by src/buildStatic.js from src/fetchLichess.js, src/process.js,
 * src/render.js, and src/browser/playerLookup.client.js. Do not edit this file
 * directly -- edit the source files above and re-run `node src/buildStatic.js`.
 *
 * This calls only Lichess's keyless public API (https://lichess.org/api)
 * directly from your browser. No Lichess API token is used, read, or present
 * anywhere in this file. */


'use strict';

/**
 * Data-fetch module for the Lichess public API (https://lichess.org/api).
 * No API key is required for the endpoints used here.
 *
 * Every exported function accepts an options object with an injectable
 * `fetchImpl` (defaulting to the global `fetch`) specifically so tests can
 * supply a fake implementation backed by fixture JSON instead of hitting
 * the live network.
 */

const BASE_URL = 'https://lichess.org';

class LichessNotFoundError extends Error {
  constructor(username) {
    super(`Lichess user not found: ${username}`);
    this.name = 'LichessNotFoundError';
    this.username = username;
  }
}

class LichessRateLimitError extends Error {
  constructor(retryAfter) {
    super(`Lichess API rate limit hit${retryAfter ? ` (retry after ${retryAfter}s)` : ''}`);
    this.name = 'LichessRateLimitError';
    this.retryAfter = retryAfter || null;
  }
}

class LichessApiError extends Error {
  constructor(status, statusText, url) {
    super(`Lichess API request failed: ${status} ${statusText} (${url})`);
    this.name = 'LichessApiError';
    this.status = status;
  }
}

/**
 * Shared response handling: maps HTTP status codes to typed errors.
 */
async function handleErrors(response, url, username) {
  if (response.status === 404) {
    throw new LichessNotFoundError(username);
  }
  if (response.status === 429) {
    const retryAfter = response.headers && typeof response.headers.get === 'function'
      ? response.headers.get('retry-after')
      : null;
    throw new LichessRateLimitError(retryAfter);
  }
  if (!response.ok) {
    throw new LichessApiError(response.status, response.statusText, url);
  }
}

/**
 * GET /api/user/:username -> profile JSON (includes perfs, counts, etc).
 */
async function fetchUserProfile(username, { fetchImpl = fetch } = {}) {
  const url = `${BASE_URL}/api/user/${encodeURIComponent(username)}`;
  const response = await fetchImpl(url, { headers: { Accept: 'application/json' } });
  await handleErrors(response, url, username);
  return response.json();
}

/**
 * GET /api/user/:username/rating-history -> array of
 * { name: <variant>, points: [[year, month0Indexed, day, rating], ...] }
 */
async function fetchRatingHistory(username, { fetchImpl = fetch } = {}) {
  const url = `${BASE_URL}/api/user/${encodeURIComponent(username)}/rating-history`;
  const response = await fetchImpl(url, { headers: { Accept: 'application/json' } });
  await handleErrors(response, url, username);
  return response.json();
}

/**
 * GET /api/games/user/:username -> newline-delimited JSON (one game per line)
 * when Accept: application/x-ndjson is sent.
 */
async function fetchRecentGames(username, { max = 10, fetchImpl = fetch } = {}) {
  const url = `${BASE_URL}/api/games/user/${encodeURIComponent(username)}?max=${encodeURIComponent(max)}&moves=false`;
  const response = await fetchImpl(url, { headers: { Accept: 'application/x-ndjson' } });
  await handleErrors(response, url, username);
  const text = await response.text();
  return text
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => JSON.parse(line));
}



'use strict';

/**
 * Pure processing/aggregation functions. No I/O here at all -- everything
 * takes plain data in and returns plain data out, which is what makes these
 * unit-testable against static fixture JSON.
 */

/**
 * Summarize a rating-history payload (as returned by
 * fetchLichess.fetchRatingHistory) into one row per variant with the stats
 * a stats page would actually want to show.
 *
 * @param {Array<{name: string, points: Array<[number, number, number, number]>}>} history
 * @returns {Array<{variant: string, current: number|null, peak: number|null,
 *   low: number|null, gamesRecorded: number, firstDate: string|null,
 *   lastDate: string|null, change: number|null}>}
 */
function summarizeRatingHistory(history) {
  if (!Array.isArray(history)) return [];

  return history
    .map((variant) => {
      const points = Array.isArray(variant.points) ? variant.points : [];
      if (points.length === 0) {
        return {
          variant: variant.name,
          current: null,
          peak: null,
          low: null,
          gamesRecorded: 0,
          firstDate: null,
          lastDate: null,
          change: null,
        };
      }

      const ratings = points.map((p) => p[3]);
      const first = points[0];
      const last = points[points.length - 1];

      return {
        variant: variant.name,
        current: last[3],
        peak: Math.max(...ratings),
        low: Math.min(...ratings),
        gamesRecorded: points.length,
        firstDate: pointToDateString(first),
        lastDate: pointToDateString(last),
        change: last[3] - first[3],
      };
    })
    // Drop variants Lichess reports with zero history points -- nothing to show.
    .filter((row) => row.gamesRecorded > 0);
}

function pointToDateString([year, month0, day]) {
  // Lichess months are 0-indexed (0 = January).
  const mm = String(month0 + 1).padStart(2, '0');
  const dd = String(day).padStart(2, '0');
  return `${year}-${mm}-${dd}`;
}

/**
 * Summarize a list of recent games (as returned by
 * fetchLichess.fetchRecentGames) relative to a given username: win/loss/draw
 * counts, win rate, average opponent rating, and a flat per-game result list
 * ready for rendering.
 *
 * @param {Array<object>} games
 * @param {string} username
 * @returns {{totalGames: number, wins: number, losses: number, draws: number,
 *   winRate: number|null, avgOpponentRating: number|null,
 *   results: Array<{opponent: string, opponentRating: number|null,
 *     result: 'win'|'loss'|'draw', color: 'white'|'black', variant: string,
 *     speed: string, date: string|null}>}}
 */
function summarizeGames(games, username) {
  if (!Array.isArray(games) || !username) {
    return { totalGames: 0, wins: 0, losses: 0, draws: 0, winRate: null, avgOpponentRating: null, results: [] };
  }

  const lowerUsername = username.toLowerCase();
  let wins = 0;
  let losses = 0;
  let draws = 0;
  let opponentRatingSum = 0;
  let opponentRatingCount = 0;

  const results = games.map((game) => {
    const players = game.players || {};
    const white = players.white || {};
    const black = players.black || {};
    const whiteName = ((white.user && white.user.name) || 'anonymous').toLowerCase();
    const isWhite = whiteName === lowerUsername;
    const me = isWhite ? white : black;
    const opponent = isWhite ? black : white;

    let result;
    if (!game.winner) {
      result = 'draw';
      draws += 1;
    } else if (game.winner === (isWhite ? 'white' : 'black')) {
      result = 'win';
      wins += 1;
    } else {
      result = 'loss';
      losses += 1;
    }

    const opponentRating = typeof opponent.rating === 'number' ? opponent.rating : null;
    if (opponentRating !== null) {
      opponentRatingSum += opponentRating;
      opponentRatingCount += 1;
    }

    return {
      opponent: (opponent.user && opponent.user.name) || 'Anonymous',
      opponentRating,
      result,
      color: isWhite ? 'white' : 'black',
      variant: game.variant || 'standard',
      speed: game.speed || 'unknown',
      date: game.createdAt ? new Date(game.createdAt).toISOString().slice(0, 10) : null,
    };
  });

  const totalGames = games.length;
  return {
    totalGames,
    wins,
    losses,
    draws,
    winRate: totalGames > 0 ? Number(((wins / totalGames) * 100).toFixed(1)) : null,
    avgOpponentRating: opponentRatingCount > 0 ? Math.round(opponentRatingSum / opponentRatingCount) : null,
    results,
  };
}



'use strict';

/**
 * Rendering layer: a pure function that turns already-processed data into an
 * HTML string. No framework, no templating engine -- just template
 * literals. Kept separate from build.js/server.js so it can be reused by
 * both the static generator and the local dev server.
 *
 * This file is also concatenated verbatim (see buildStatic.js's
 * bundleBrowserModule) into the client-side bundle that runs directly in a
 * visitor's browser for the static player-lookup page. That means it MUST
 * NOT use CommonJS module loading anywhere at the top level -- there is no
 * such loader in that context. The shared design system below (SITE_CSS
 * / FAVICON_DATA_URI) is therefore defined as plain constants right here,
 * not pulled in from a separate module, so render.js stays the single
 * source of truth for markup AND styling that both server.js and
 * buildStatic.js import from, with nothing to drift.
 */

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Shared design tokens + component styles, used identically by every page
 * across both the local dev server (src/server.js) and the static build
 * (dist/*.html via src/buildStatic.js). One palette, deliberately: a
 * restrained, chess-appropriate ink-and-parchment scheme (no dark-mode
 * toggle -- see task scope).
 */
const SITE_CSS = `
  :root {
    --font-sans: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    --font-serif: Georgia, "Iowan Old Style", "Palatino Linotype", "Times New Roman", serif;

    --color-bg: #f5f1e6;
    --color-surface: #ffffff;
    --color-surface-alt: #ece3cd;
    --color-border: #ddd0ac;
    --color-text: #23271f;
    --color-muted: #6b6a5c;
    --color-accent: #3c6e52;
    --color-accent-dark: #2a4d3a;
    --color-accent-contrast: #f8f5ea;
    --color-hover: rgba(60, 110, 82, 0.08);
    --color-focus: #c97a2e;

    --color-win: #2f7d43;
    --color-win-bg: #e3f2e6;
    --color-draw: #93731c;
    --color-draw-bg: #f4ecd2;
    --color-loss: #b23b30;
    --color-loss-bg: #fbe4e0;

    --text-xs: 0.75rem;
    --text-sm: 0.875rem;
    --text-base: 1rem;
    --text-md: 1.125rem;
    --text-lg: 1.375rem;
    --text-xl: 1.875rem;
    --text-2xl: 2.25rem;

    --space-1: 0.25rem;
    --space-2: 0.5rem;
    --space-3: 0.75rem;
    --space-4: 1rem;
    --space-5: 1.5rem;
    --space-6: 2rem;
    --space-7: 3rem;

    --radius-sm: 6px;
    --radius-md: 10px;
    --radius-lg: 16px;
    --radius-pill: 999px;

    --shadow-sm: 0 1px 2px rgba(35, 39, 31, 0.08);
    --shadow-md: 0 8px 24px rgba(35, 39, 31, 0.10);
  }

  * { box-sizing: border-box; }

  html { background: var(--color-bg); }

  body {
    font-family: var(--font-sans);
    background: var(--color-bg);
    color: var(--color-text);
    max-width: 880px;
    margin: 0 auto;
    padding: var(--space-5) var(--space-4) var(--space-7);
    line-height: 1.55;
    font-size: var(--text-base);
  }

  main { display: block; }

  a { color: var(--color-accent-dark); }
  a:hover { color: var(--color-accent); }

  :focus-visible {
    outline: 3px solid var(--color-focus);
    outline-offset: 2px;
    border-radius: var(--radius-sm);
  }

  .site-header {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    justify-content: space-between;
    gap: var(--space-3);
    padding-bottom: var(--space-4);
    margin-bottom: var(--space-5);
    border-bottom: 2px solid var(--color-border);
  }

  .brand {
    font-family: var(--font-serif);
    font-weight: 700;
    font-size: var(--text-md);
    color: var(--color-accent-dark);
    letter-spacing: 0.01em;
    display: inline-flex;
    align-items: center;
    gap: var(--space-2);
  }

  .brand-mark {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 1.6em;
    height: 1.6em;
    border-radius: var(--radius-pill);
    background: var(--color-accent-dark);
    color: var(--color-accent-contrast);
    font-size: 0.95em;
  }

  .site-nav { display: flex; gap: var(--space-2); flex-wrap: wrap; }

  .site-nav a {
    color: var(--color-text);
    text-decoration: none;
    font-size: var(--text-sm);
    font-weight: 600;
    padding: var(--space-2) var(--space-3);
    border-radius: var(--radius-sm);
    transition: background-color 120ms ease, color 120ms ease;
  }

  .site-nav a:hover { background: var(--color-hover); color: var(--color-accent-dark); }
  .site-nav a[aria-current="page"] { background: var(--color-accent-dark); color: var(--color-accent-contrast); }

  h1, h2, h3 { font-family: var(--font-serif); color: var(--color-accent-dark); line-height: 1.2; }
  h1.page-title { font-size: var(--text-2xl); margin: 0; }
  h2 { font-size: var(--text-lg); margin: var(--space-6) 0 var(--space-3); }
  h3 { font-size: var(--text-md); margin: var(--space-5) 0 var(--space-2); }

  .subtitle { color: var(--color-muted); margin: var(--space-2) 0 0; font-size: var(--text-base); }

  .empty-note {
    color: var(--color-muted);
    background: var(--color-surface-alt);
    border: 1px dashed var(--color-border);
    border-radius: var(--radius-md);
    padding: var(--space-4);
  }

  .table-hint {
    display: none;
    font-size: var(--text-xs);
    color: var(--color-muted);
    margin: 0 0 var(--space-2);
  }

  .table-scroll {
    overflow-x: auto;
    border: 1px solid var(--color-border);
    border-radius: var(--radius-md);
    box-shadow: var(--shadow-sm);
    margin: var(--space-3) 0 var(--space-6);
    background: var(--color-surface);
  }

  table {
    width: 100%;
    min-width: 480px;
    border-collapse: collapse;
    font-size: var(--text-sm);
  }

  thead th {
    text-align: left;
    padding: var(--space-3) var(--space-4);
    background: var(--color-accent-dark);
    color: var(--color-accent-contrast);
    font-weight: 600;
    font-size: var(--text-xs);
    text-transform: uppercase;
    letter-spacing: 0.04em;
    white-space: nowrap;
  }

  tbody td {
    padding: var(--space-3) var(--space-4);
    border-bottom: 1px solid var(--color-border);
  }

  tbody tr:last-child td { border-bottom: none; }
  tbody tr:nth-child(even) { background: var(--color-surface-alt); }
  tbody tr:hover td { background: var(--color-hover); }

  tr.result-win td:first-child { box-shadow: inset 3px 0 0 var(--color-win); }
  tr.result-loss td:first-child { box-shadow: inset 3px 0 0 var(--color-loss); }
  tr.result-draw td:first-child { box-shadow: inset 3px 0 0 var(--color-draw); }

  .delta { font-weight: 700; }
  .delta--pos { color: var(--color-win); }
  .delta--neg { color: var(--color-loss); }
  .delta--zero { color: var(--color-muted); }

  .badge {
    display: inline-block;
    padding: 0.15em 0.6em;
    border-radius: var(--radius-pill);
    font-size: var(--text-xs);
    font-weight: 700;
    letter-spacing: 0.02em;
  }
  .badge--win { background: var(--color-win-bg); color: var(--color-win); }
  .badge--loss { background: var(--color-loss-bg); color: var(--color-loss); }
  .badge--draw { background: var(--color-draw-bg); color: var(--color-draw); }

  .summary-line {
    color: var(--color-muted);
    margin: var(--space-2) 0 var(--space-4);
  }

  .lookup-form {
    display: flex;
    flex-wrap: wrap;
    gap: var(--space-3);
    margin: var(--space-4) 0 var(--space-6);
  }

  .lookup-form label {
    display: flex;
    flex-direction: column;
    gap: var(--space-1);
    font-size: var(--text-sm);
    color: var(--color-muted);
  }

  .lookup-form input,
  .lookup-form select {
    flex: 1 1 240px;
    font: inherit;
    font-size: var(--text-base);
    padding: var(--space-3) var(--space-4);
    border: 1.5px solid var(--color-border);
    border-radius: var(--radius-md);
    background: var(--color-surface);
    color: var(--color-text);
    transition: border-color 120ms ease, box-shadow 120ms ease;
  }

  .lookup-form input:hover,
  .lookup-form select:hover { border-color: var(--color-accent); }
  .lookup-form input:focus-visible,
  .lookup-form select:focus-visible {
    border-color: var(--color-accent);
    box-shadow: 0 0 0 3px var(--color-hover);
    outline: none;
  }

  .lookup-form button {
    font: inherit;
    font-size: var(--text-base);
    font-weight: 700;
    padding: var(--space-3) var(--space-5);
    border: none;
    border-radius: var(--radius-md);
    background: var(--color-accent-dark);
    color: var(--color-accent-contrast);
    cursor: pointer;
    transition: background-color 120ms ease, transform 120ms ease;
  }

  .lookup-form button:hover { background: var(--color-accent); }
  .lookup-form button:active { transform: translateY(1px); }

  .status-message {
    border-radius: var(--radius-md);
    padding: var(--space-4) var(--space-5);
    margin: var(--space-3) 0 var(--space-6);
    font-size: var(--text-base);
  }

  .status-message--loading {
    background: var(--color-surface-alt);
    color: var(--color-muted);
    display: flex;
    align-items: center;
    gap: var(--space-3);
  }

  .status-message--loading::before {
    content: "";
    width: 1.1em;
    height: 1.1em;
    border-radius: var(--radius-pill);
    border: 2.5px solid var(--color-border);
    border-top-color: var(--color-accent);
    animation: spin 800ms linear infinite;
  }

  .status-message--error {
    background: var(--color-loss-bg);
    color: var(--color-loss);
    border: 1px solid var(--color-loss);
    font-weight: 600;
  }

  @keyframes spin { to { transform: rotate(360deg); } }

  .move-chip {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    padding: 0.1em 0.6em;
    border-radius: var(--radius-sm);
    font-family: var(--font-serif);
    font-weight: 700;
    font-size: var(--text-sm);
  }

  .move-chip--white {
    background: var(--color-surface);
    border: 1.5px solid var(--color-accent-dark);
    color: var(--color-accent-dark);
  }

  .move-chip--black {
    background: var(--color-accent-dark);
    border: 1.5px solid var(--color-accent-dark);
    color: var(--color-accent-contrast);
  }

  .wdl-bar {
    display: inline-flex;
    width: 110px;
    height: 8px;
    border-radius: var(--radius-pill);
    overflow: hidden;
    background: var(--color-border);
    vertical-align: middle;
  }

  .wdl-seg--win { background: var(--color-win); height: 100%; }
  .wdl-seg--draw { background: var(--color-draw); height: 100%; }
  .wdl-seg--loss { background: var(--color-loss); height: 100%; }

  .wdl-label { font-size: var(--text-xs); color: var(--color-muted); }

  .repertoire-intro { color: var(--color-muted); margin: 0 0 var(--space-5); }

  ul.repertoire-tree, ul.repertoire-tree ul {
    list-style: none;
    margin: 0;
    padding-left: var(--space-5);
    border-left: 2px solid var(--color-border);
  }
  ul.repertoire-tree { padding-left: 0; border-left: none; }

  .repertoire-tree li { margin: var(--space-3) 0; }

  .rep-node-row {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: var(--space-3);
    background: var(--color-surface);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-md);
    padding: var(--space-2) var(--space-4);
    box-shadow: var(--shadow-sm);
  }

  .rep-games { font-size: var(--text-sm); color: var(--color-text); }
  .rep-pct { color: var(--color-muted); }
  .rep-rating { color: var(--color-muted); font-size: var(--text-xs); }

  footer.site-footer {
    color: var(--color-muted);
    font-size: var(--text-xs);
    margin-top: var(--space-7);
    padding-top: var(--space-4);
    border-top: 1px solid var(--color-border);
  }

  @media (max-width: 640px) {
    body { padding: var(--space-4) var(--space-3) var(--space-6); }
    h1.page-title { font-size: var(--text-xl); }
    .table-hint { display: block; }
    .wdl-bar { width: 72px; }
    .rep-node-row { padding: var(--space-2) var(--space-3); }
    .lookup-form { flex-direction: column; align-items: stretch; }
  }
`;

/**
 * A minimalist chess-pawn favicon as an inline SVG data URI -- no external
 * asset, no build step. Colors are hardcoded here (not pulled from the CSS
 * tokens above) because a favicon is loaded by the browser as its own
 * standalone resource and does not inherit the page's CSS custom
 * properties; they're kept visually in sync with --color-accent-dark /
 * --color-accent-contrast by hand.
 */
const FAVICON_DATA_URI = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Ccircle cx='32' cy='32' r='30' fill='%232a4d3a'/%3E%3Ccircle cx='32' cy='23' r='9' fill='%23f8f5ea'/%3E%3Cpath d='M21 40c0-3 4-5 11-5s11 2 11 5l3 9H18z' fill='%23f8f5ea'/%3E%3Crect x='15' y='50' width='34' height='8' rx='3' fill='%23f8f5ea'/%3E%3C/svg%3E";

/**
 * @param {string} title document <title>
 * @returns {string} a full <head>...</head> block shared by every page.
 */
function renderDocumentHead(title) {
  return `<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <link rel="icon" href="${FAVICON_DATA_URI}">
  <style>${SITE_CSS}</style>
</head>`;
}

/**
 * @param {{player: string, repertoire: string}} nav link targets -- either
 *   the dynamic dev-server routes (server.js's default) or flat static
 *   filenames (buildStatic.js).
 * @param {'player'|'repertoire'|null} [active] which nav link, if any,
 *   represents the current page.
 * @returns {string} the shared header/nav markup used on every page.
 */
function renderHeader(nav, active = null) {
  return `<header class="site-header">
    <span class="brand"><span class="brand-mark" aria-hidden="true">&#9822;</span>Lichess Stats</span>
    <nav class="site-nav">
      <a href="${escapeHtml(nav.player)}"${active === 'player' ? ' aria-current="page"' : ''}>Player lookup</a>
      <a href="${escapeHtml(nav.repertoire)}"${active === 'repertoire' ? ' aria-current="page"' : ''}>Repertoire explorer</a>
    </nav>
  </header>`;
}

/**
 * @param {string} innerHtml page-specific footer copy (data-source credit,
 *   etc). Callers should NOT claim the site is only local/unpublished --
 *   this app is deployed to GitHub Pages.
 */
function renderFooter(innerHtml) {
  return `<footer class="site-footer">${innerHtml}</footer>`;
}

/**
 * Wraps a `<table>...</table>` string in a horizontally-scrollable
 * container with a visible "there's more, scroll" affordance on narrow
 * viewports, instead of letting the table silently overflow the page.
 */
function wrapTable(tableHtml) {
  return `
    <p class="table-hint">Scroll to see more &rarr;</p>
    <div class="table-scroll" tabindex="0" role="region" aria-label="Scrollable data table">${tableHtml}</div>`;
}

function deltaClassFor(change) {
  if (change == null) return 'delta--zero';
  if (change > 0) return 'delta--pos';
  if (change < 0) return 'delta--neg';
  return 'delta--zero';
}

function renderRatingTable(ratingRows) {
  if (ratingRows.length === 0) {
    return '<p class="empty-note">No rating history found.</p>';
  }
  const rows = ratingRows
    .map((row) => {
      const deltaText = row.change == null ? '-' : `${row.change >= 0 ? '+' : ''}${row.change}`;
      return `
      <tr>
        <td>${escapeHtml(row.variant)}</td>
        <td>${row.current ?? '-'}</td>
        <td>${row.peak ?? '-'}</td>
        <td>${row.low ?? '-'}</td>
        <td class="delta ${deltaClassFor(row.change)}">${deltaText}</td>
        <td>${row.gamesRecorded}</td>
      </tr>`;
    })
    .join('');

  return wrapTable(`
    <table>
      <thead>
        <tr><th>Variant</th><th>Current</th><th>Peak</th><th>Low</th><th>Change</th><th>Data points</th></tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>`);
}

function resultBadge(result) {
  const label = result === 'win' ? 'Win' : result === 'loss' ? 'Loss' : 'Draw';
  return `<span class="badge badge--${escapeHtml(result)}">${label}</span>`;
}

function renderGamesTable(gameSummary) {
  if (gameSummary.totalGames === 0) {
    return '<p class="empty-note">No recent games found.</p>';
  }
  const rows = gameSummary.results
    .map(
      (r) => `
      <tr class="result-${r.result}">
        <td>${r.date || '-'}</td>
        <td>${escapeHtml(r.opponent)}</td>
        <td>${r.opponentRating ?? '-'}</td>
        <td>${escapeHtml(r.color)}</td>
        <td>${escapeHtml(r.variant)} / ${escapeHtml(r.speed)}</td>
        <td>${resultBadge(r.result)}</td>
      </tr>`
    )
    .join('');

  return `
    <p class="summary-line">${gameSummary.wins}W / ${gameSummary.losses}L / ${gameSummary.draws}D
       out of ${gameSummary.totalGames} games (win rate ${gameSummary.winRate}%,
       avg opponent rating ${gameSummary.avgOpponentRating ?? 'n/a'})</p>` +
    wrapTable(`
    <table>
      <thead>
        <tr><th>Date</th><th>Opponent</th><th>Opp. rating</th><th>Color</th><th>Variant/Speed</th><th>Result</th></tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>`);
}

/**
 * @param {{username: string, ratingRows: Array, gameSummary: object,
 *   nav?: {player: string, repertoire: string}}} data
 * @returns {string} a full standalone HTML document
 */
function renderPlayerPage({ username, ratingRows, gameSummary, nav = { player: '/', repertoire: '/repertoire' } }) {
  return `<!DOCTYPE html>
<html lang="en">
${renderDocumentHead(`${username} - Lichess stats`)}
<body>
  ${renderHeader(nav, 'player')}
  <main>
    <h1 class="page-title">${escapeHtml(username)}</h1>
    <p class="subtitle">Lichess rating history and recent games</p>

    <h2>Ratings by variant</h2>
    ${renderRatingTable(ratingRows)}

    <h2>Recent games</h2>
    ${renderGamesTable(gameSummary)}
  </main>
  ${renderFooter('Data source: <a href="https://lichess.org/api">lichess.org/api</a>.')}
</body>
</html>
`;
}

function renderRepertoireNode(node) {
  const winPct = typeof node.winPct === 'number' ? node.winPct : null;
  const drawPct = typeof node.drawPct === 'number' ? node.drawPct : null;
  const lossPct = typeof node.lossPct === 'number' ? node.lossPct : null;
  const ratingNote = node.averageRating ? `<span class="rep-rating">avg rating ${node.averageRating}</span>` : '';
  const children = node.children && node.children.length > 0
    ? `<ul>${node.children.map(renderRepertoireNode).join('')}</ul>`
    : '';
  const wdlTitle = `${node.mover} win/draw/loss: ${winPct ?? '-'}% / ${drawPct ?? '-'}% / ${lossPct ?? '-'}%`;
  const wdlBar = winPct == null
    ? ''
    : `<span class="wdl-bar" title="${escapeHtml(wdlTitle)}">
        <span class="wdl-seg--win" style="width:${winPct}%"></span>
        <span class="wdl-seg--draw" style="width:${drawPct}%"></span>
        <span class="wdl-seg--loss" style="width:${lossPct}%"></span>
      </span>
      <span class="wdl-label">${winPct}% / ${drawPct}% / ${lossPct}%</span>`;

  return `
    <li>
      <div class="rep-node-row">
        <span class="move-chip move-chip--${escapeHtml(node.mover)}">${escapeHtml(node.san)}</span>
        <span class="rep-games">${node.games.toLocaleString()} games <span class="rep-pct">(${node.playedPct ?? '-'}% of this position)</span></span>
        ${wdlBar}
        ${ratingNote}
      </div>
      ${children}
    </li>`;
}

function renderRepertoireTree(tree) {
  if (!Array.isArray(tree) || tree.length === 0) {
    return '<p class="empty-note">No repertoire data found for this rating band and color.</p>';
  }
  return `<ul class="repertoire-tree">${tree.map(renderRepertoireNode).join('')}</ul>`;
}

/**
 * @param {{ratingBand: string, color: string, opening: {eco:string,name:string}|null,
 *   totals: {white:number,draws:number,black:number}|null, tree: Array,
 *   nav?: {player: string, repertoire: string}}} data `nav` lets callers point
 *   the top-of-page links at either the dynamic dev-server routes (the
 *   default, used by server.js) or flat static filenames (used by the
 *   static build, e.g. {player: 'player.html', repertoire: 'index.html'}).
 * @returns {string} a full standalone HTML document
 */
function renderRepertoirePage({ ratingBand, color, opening, totals, tree, nav = { player: '/', repertoire: '/repertoire' } }) {
  const totalGames = totals ? totals.white + totals.draws + totals.black : null;
  const openingNote = opening ? ` &mdash; starting from ${escapeHtml(opening.name)} (${escapeHtml(opening.eco)})` : '';
  const totalsNote = totals
    ? `<p class="summary-line">${totalGames.toLocaleString()} games played from the starting position in this rating band
        (${totals.white.toLocaleString()}W / ${totals.draws.toLocaleString()}D / ${totals.black.toLocaleString()}L).</p>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
${renderDocumentHead(`Opening repertoire explorer (${ratingBand}, ${color}) - Lichess stats`)}
<body>
  ${renderHeader(nav, 'repertoire')}
  <main>
    <h1 class="page-title">Opening repertoire explorer</h1>
    <p class="subtitle">Rating band ${escapeHtml(ratingBand)}, playing as ${escapeHtml(color)}${openingNote}</p>
    ${totalsNote}
    <p class="repertoire-intro">Most-played moves at each ply for players in this rating band, with win/draw/loss rates per move.
       Your color's plies show the top choices actually played at this rating; the opponent's replies show
       only their single most common response, to keep the tree readable.</p>
    ${renderRepertoireTree(tree)}
  </main>
  ${renderFooter('Data source: <a href="https://lichess.org/api#tag/Opening-Explorer">Lichess Opening Explorer API</a> (explorer.lichess.ovh, keyless, no account required).')}
</body>
</html>
`;
}


'use strict';

/**
 * Page controller for the static player-lookup page (dist/player.html).
 *
 * This file is NOT loaded via CommonJS module loading -- it's appended as plain text
 * after fetchLichess.js, process.js, and render.js by
 * buildStatic.js's buildPlayerLookupBundle(), so it runs in the same
 * top-level scope and can call fetchRatingHistory / fetchRecentGames /
 * summarizeRatingHistory / summarizeGames / renderRatingTable /
 * renderGamesTable / escapeHtml / LichessNotFoundError / LichessRateLimitError
 * / LichessApiError directly, without any import statement.
 *
 * It calls Lichess's already-public, keyless general API
 * (https://lichess.org/api) directly from the visitor's browser. No Lichess
 * API token is used, read, or referenced anywhere in this file.
 *
 * Wrapped in an IIFE only to keep its own helper names (lookupPlayer, $,
 * etc.) out of the shared top-level scope the bundled modules above it use;
 * it still reads their declarations via normal closure/script-scope lookup.
 */
(function () {
  function $(selector) {
    return document.querySelector(selector);
  }

  function setStatus(html) {
    $('#result').innerHTML = html;
  }

  async function lookupPlayer(username) {
    setStatus('<p class="status-message status-message--loading">Loading&hellip;</p>');
    try {
      const [history, games] = await Promise.all([
        fetchRatingHistory(username),
        fetchRecentGames(username, { max: 15 }),
      ]);
      const ratingRows = summarizeRatingHistory(history);
      const gameSummary = summarizeGames(games, username);
      setStatus(`
        <h2>${escapeHtml(username)}</h2>
        <h3>Ratings by variant</h3>
        ${renderRatingTable(ratingRows)}
        <h3>Recent games</h3>
        ${renderGamesTable(gameSummary)}
      `);
    } catch (err) {
      if (err instanceof LichessNotFoundError) {
        setStatus(`<p class="status-message status-message--error">No such Lichess user: ${escapeHtml(username)}</p>`);
      } else if (err instanceof LichessRateLimitError) {
        setStatus('<p class="status-message status-message--error">Lichess API rate limit hit, try again shortly.</p>');
      } else if (err instanceof LichessApiError) {
        setStatus(`<p class="status-message status-message--error">Lichess API request failed: ${escapeHtml(err.message)}</p>`);
      } else if (err instanceof TypeError) {
        // A raw fetch()/network failure (offline, CORS block, etc) surfaces
        // as a TypeError with no useful HTTP status attached.
        setStatus(`<p class="status-message status-message--error">Could not reach the Lichess API from this page (network error or the browser blocked the cross-origin request). Details: ${escapeHtml(err.message)}</p>`);
      } else {
        setStatus(`<p class="status-message status-message--error">Lookup failed: ${escapeHtml(err.message)}</p>`);
      }
    }
  }

  function init() {
    const form = $('#lookup-form');
    if (!form) return;
    form.addEventListener('submit', (event) => {
      event.preventDefault();
      const username = $('#username').value.trim();
      if (!username) return;
      const url = new URL(window.location.href);
      url.searchParams.set('username', username);
      window.history.replaceState(null, '', url);
      lookupPlayer(username);
    });

    const params = new URLSearchParams(window.location.search);
    const prefill = params.get('username');
    if (prefill) {
      $('#username').value = prefill;
      lookupPlayer(prefill);
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
