'use strict';

/**
 * The single runtime read path for WS-1's pre-baked band-meta shards
 * (the WS-1 spec section 2.1). Every WS-1 surface
 * that needs "what does my rating band actually play here" -- the
 * Repertoire Builder's live reply table, the Personal Opening Report's
 * band-vs-your-move comparison, the Drill Engine's band-seeded cards --
 * calls lookup() here, never fetches dist/data/rep/ directly. That keeps
 * the shard wire format, the in-memory cache, and the side-to-move scoring
 * convention defined in exactly one place.
 *
 * SAME-ORIGIN TRUST NOTE (spec 3.7 N4): the shard JSON this module fetches
 * is same-origin and generated by our own build (scripts/buildBandShards.js)
 * -- it is trusted by provenance, not treated as adversarial visitor input.
 * It is still parsed defensively (try/catch around fetch/json, and
 * bandShards.isValidShard()'s `v === 1` shape check) because a stale
 * cached shard from a previous schema version, or a partial/interrupted
 * write, is a real non-adversarial failure mode worth degrading gracefully
 * from -- not because the file is considered untrusted the way a visitor-
 * supplied value is.
 *
 * FILE:// INVARIANT NOTE: this module's `fetch()` call breaks the site's
 * usual "every page works opened directly via a file:// URL" invariant for
 * any page that uses it -- the same precedent src/ecoExplorerData.js's own
 * FEN reverse-lookup fetch already set. Declare this in that page's
 * TESTING.md; it is not a defect to fix here.
 */

const { Chess } = require('chess.js');
const { shardKeyFor, decodePositionRecord, isValidShard, posKeyFor } = require('../bandShards');
// buildPackCore.js, not buildPack.js -- the latter requires ./explorerSource
// (fs/path) at module load, which breaks any browser bundle that needs this
// pure helper (see buildPackCore.js's own header comment for the full
// explanation; fixed as part of WS-1's Repertoire Builder task after the
// real esbuild bundle of this exact module reproduced the failure).
const { applyExplorerUci } = require('../buildPackCore');
const { scoreInterval } = require('../stats');

const SHARD_BASE_PATH = '/data/rep';

// shardKey cache scoped per (band, shardKey) pair -- "one fetch() per shard
// per session" (spec 2.1). Caches the in-flight/resolved Promise itself
// (not just the resolved value) so two lookup() calls issued back-to-back
// for the same shard before the first one resolves still share one
// network request rather than racing two.
const shardCache = new Map();

function defaultFetchImpl() {
  if (typeof window !== 'undefined' && typeof window.fetch === 'function') return window.fetch.bind(window);
  if (typeof fetch === 'function') return fetch;
  return null;
}

/**
 * @param {string} band
 * @param {string} shardKey
 * @returns {string} site-root-relative URL, matching
 *   scripts/buildBandShards.js's `dist/data/rep/<band>/<shardKey>.json`
 *   output path.
 */
function shardUrl(band, shardKey) {
  return `${SHARD_BASE_PATH}/${encodeURIComponent(band)}/${encodeURIComponent(shardKey)}.json`;
}

/**
 * @returns {Promise<object|null>} the parsed, shape-valid Shard, or `null`
 *   on any fetch failure, non-200 response, unparseable JSON, or a shard
 *   that fails isValidShard() -- every one of those collapses to the same
 *   "no data available" outcome for lookup() below, which is what turns
 *   into `coverage: 'unavailable'`.
 */
function fetchShard(band, shardKey, fetchImpl) {
  const cacheKey = `${band}/${shardKey}`;
  if (shardCache.has(cacheKey)) return shardCache.get(cacheKey);

  const promise = (async () => {
    try {
      const res = await fetchImpl(shardUrl(band, shardKey));
      if (!res || !res.ok) return null;
      const json = await res.json();
      return isValidShard(json) ? json : null;
    } catch (err) {
      return null;
    }
  })();

  shardCache.set(cacheKey, promise);
  return promise;
}

/**
 * SAN for a candidate UCI move at the position `chess` currently holds --
 * applies it (via buildPack.js's applyExplorerUci, for the same Explorer
 * castling-encoding reason every other WS-1/M2 consumer uses it), reads the
 * SAN chess.js reports, then always undoes the move so `chess` is left
 * exactly as it was for the next candidate. Returns the raw uci string
 * (never null/throws) if the move can't be replayed, so one bad shard
 * record degrades a single row rather than the whole lookup.
 */
function sanFor(chess, uci) {
  try {
    const result = applyExplorerUci(chess, uci);
    if (!result) return uci;
    chess.undo();
    return result.san;
  } catch (err) {
    return uci;
  }
}

/**
 * @param {{play?: string[], band: string, pool: string, fetchImpl?: Function}} args
 *   `fetchImpl` defaults to the global `fetch` -- injectable for tests
 *   (same convention as every other fetchImpl-shaped function in this
 *   codebase) and for the (rare) case this runs in a context with no
 *   `fetch` at all, which resolves to `coverage: 'unavailable'` rather than
 *   throwing.
 * @returns {Promise<{coverage: 'in'|'out-of-book'|'unavailable',
 *   total: {w:number, d:number, b:number}, games: number,
 *   moves: Array<{uci:string, san:string, games:number, playedPct:number|null,
 *   score:number, scoreLo:number, scoreHi:number}>,
 *   retrieved: string|null, source: string|null}>}
 */
async function lookup({ play = [], band, pool, fetchImpl = defaultFetchImpl() } = {}) {
  const UNAVAILABLE = { coverage: 'unavailable', total: { w: 0, d: 0, b: 0 }, games: 0, moves: [], retrieved: null, source: null };
  if (!fetchImpl) return UNAVAILABLE;

  const shardKey = shardKeyFor(play);
  const shard = await fetchShard(band, shardKey, fetchImpl);
  if (!shard) return UNAVAILABLE;

  const { posKey } = posKeyFor(play);
  const record = shard.positions[posKey];
  if (!record) {
    // First-class, designed state (spec 2.1): the crawl's reach/n/ply
    // thresholds stop well short of every position a real game can reach.
    // Not an error -- every one of WS-1's three surfaces must render this
    // deliberately, never as a blank/broken table.
    return { coverage: 'out-of-book', total: { w: 0, d: 0, b: 0 }, games: 0, moves: [], retrieved: shard.retrieved, source: shard.source };
  }

  const decoded = decodePositionRecord(record);
  const games = decoded.w + decoded.d + decoded.b;

  const chess = new Chess();
  for (const uci of play) {
    try {
      applyExplorerUci(chess, uci);
    } catch (err) {
      // `play` reaching this module always comes from a real chess.js board
      // a visitor has actually played legal moves on (never unvalidated
      // free text) -- see this module's header note and bandShards.js's
      // posKeyFor() doc comment. A replay failure here means posKey above
      // already resolved against a position this loop can't reach; fall
      // through with whatever squares `chess` reached so SAN lookup below
      // degrades to raw UCI strings rather than throwing.
      break;
    }
  }
  const sideToMove = chess.turn(); // 'w' | 'b', AFTER replaying `play`, BEFORE any candidate move.

  const moves = decoded.moves.map((m) => {
    const moveGames = m.w + m.d + m.b;
    // "score from the side to move" (spec 2.1): white-to-move scores on
    // (white wins, draws, black wins); black-to-move scores on the mirror.
    const interval = sideToMove === 'w' ? scoreInterval(m.w, m.d, m.b) : scoreInterval(m.b, m.d, m.w);
    return {
      uci: m.uci,
      san: sanFor(chess, m.uci),
      games: moveGames,
      playedPct: games > 0 ? moveGames / games : null,
      score: interval.score,
      scoreLo: interval.low,
      scoreHi: interval.high,
    };
  });

  return {
    coverage: 'in',
    total: { w: decoded.w, d: decoded.d, b: decoded.b },
    games,
    moves,
    retrieved: shard.retrieved,
    source: shard.source,
  };
}

/** Test-only escape hatch -- clears the module-level shard cache. */
function clearCache() {
  shardCache.clear();
}

module.exports = { lookup, shardUrl, clearCache };
