'use strict';

/**
 * Run-by-hand resumable crawler that builds the WS-1 band-meta shard
 * dataset (the WS-1 spec section 2.1) -- same
 * convention as the already-shipped scripts/buildPacks.js and
 * scripts/build-og-image.js: NOT part of `npm run build:static`, invoked by
 * hand when the dataset needs to be built or refreshed.
 *
 * WHY THIS EXISTS (spec section 4.1, restated briefly): the Lichess Opening
 * Explorer now requires a personal access token (src/fetchOpeningExplorer.js
 * header comment), and a token can never ship to the browser
 * (security-standards.md). The Repertoire Builder and Personal Opening
 * Report therefore cannot query band meta live from a visitor's browser --
 * band meta must be pre-baked into static JSON, generated here, and served
 * from dist/data/rep/ (read at runtime by src/browser/bandData.client.js).
 *
 * OUTPUT LOCATION: this script writes to data/rep/ (a SOURCE directory,
 * committed to git -- see that directory's own README.md), NOT directly
 * into dist/. Spec 2.1 is explicit that shard output "is COMMITTED to the
 * repo ... the deploy build must not depend on a live crawl," and dist/ is
 * entirely gitignored and wiped/regenerated by every `npm run build:static`
 * run (src/buildStatic.js's own header comment) -- committing straight into
 * dist/ would either fight that regeneration or require carving a
 * gitignore exception into an otherwise-fully-generated directory. Instead
 * this follows the SAME convention data/aggregates/ and data/eco/ already
 * use: a committed data/ subdirectory, copied into dist/data/rep/ at build
 * time by src/buildStatic.js's copyBandShardsToDist() (mirroring that
 * module's existing copyAggregateShardsToDist() for the dump pipeline's
 * data/aggregates/ -> dist/data/ copy). Unlike data/aggregates/ (excluded
 * from git, published as a GitHub Release asset instead -- see
 * .gitignore's own comment for why), data/rep/ IS committed, because spec
 * 2.1 asks for exactly that.
 *
 * ALGORITHM -- reach-weighted best-first expansion from the start position:
 *   reach(root) = 1.0
 *   reach(child) = reach(parent) * (child move's games / parent's total games)
 *   Expand the highest-reach unexpanded frontier node first.
 * STOP CONDITIONS (checked per node, before it counts against the budget):
 *   reach < MIN_REACH, OR ply > MAX_PLY, OR (after fetching) games < MIN_GAMES
 *   at that node, OR the band's position budget is hit.
 * RATE LIMITING (Non-Negotiable 3, written as code, not a suggestion):
 *   sequential requests only, minimum 1000ms between requests, hard stop
 *   after 3 consecutive 429s, Retry-After honoured on every 429.
 * RESUMABLE: a per-band checkpoint JSON (.cache/band-shards/<band>.checkpoint.json)
 *   of the frontier + already-expanded positions, so an interrupted or
 *   rate-limited run continues instead of re-crawling from scratch. The
 *   existing on-disk Explorer response cache (.cache/explorer/) is a SECOND
 *   layer of the same protection (spec 2.1) -- even a checkpoint-less
 *   restart re-fetches nothing already cached there.
 *
 * Usage: node scripts/buildBandShards.js [--band <band>] [--budget <n>]
 *   [--no-cache] [--strict-budget]
 *   --band          crawl only this RATING_BANDS key (repeatable-by-rerun;
 *                   default: all 4 bands, one after another).
 *   --budget        per-band position budget, default 1500.
 *   --no-cache      bypass the on-disk Explorer response cache (forces a
 *                   fresh live request even for a URL already cached).
 *   --strict-budget throw (fail the run) instead of printing a WARN if a
 *                   shard exceeds the 120 KB per-shard budget or a band
 *                   exceeds the 6 MB per-band-directory budget -- off by
 *                   default so a multi-hour run's very last write doesn't
 *                   discard everything it already produced over one
 *                   oversized shard; every written file is real either way.
 */

const fs = require('fs');
const path = require('path');
const { RATING_BANDS } = require('../src/processRepertoire');
const { fetchMoves } = require('../src/explorerSource');
const { withExplorerCache } = require('../src/explorerCache');
const {
  posKeyFor,
  shardKeyFor,
  positionRecordFrom,
  buildShard,
  SOURCE_EXPLORER,
} = require('../src/bandShards');

const POOL = 'blitz';
// Deliberately NOT processRepertoire.js's DEFAULT_SPEEDS (['blitz','rapid'])
// -- that blend is exactly the unstated blitz+rapid mixing
// src/explorerSource.js's own header comment names as an existing audit
// defect (a blended draw rate the site never used to disclose as blended).
// This new pipeline states its pool honestly in every shard's `pool` field,
// so it must actually query one pool, not a blend.
const SPEEDS = ['blitz'];
const MOVES_PER_REQUEST = 12;

const MIN_REACH = 0.002;
const MIN_GAMES = 300;
const MAX_PLY = 12;
const DEFAULT_BUDGET_PER_BAND = 1500;

const REQUEST_SPACING_MS = 1000;
const MAX_CONSECUTIVE_429 = 3;
const CHECKPOINT_SAVE_EVERY = 25;

const MAX_SHARD_BYTES = 120 * 1024;
const MAX_BAND_DIR_BYTES = 6 * 1024 * 1024;

const OUT_DIR = path.join(__dirname, '..', 'data', 'rep');
const CHECKPOINT_DIR = path.join(__dirname, '..', '.cache', 'band-shards');

class HardStopError extends Error {}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Politely spaced fetch wrapper: minimum REQUEST_SPACING_MS between any two
 * live requests it actually issues, honours Retry-After on a 429, and
 * throws HardStopError after MAX_CONSECUTIVE_429 in a row (Non-Negotiable
 * 3 -- "hard stop after 3 consecutive 429s"). A cache hit (withExplorerCache
 * wraps THIS function, not the other way around) never reaches here at all,
 * so resuming from cache costs no pacing delay.
 */
function createRateLimitedFetch() {
  let consecutive429 = 0;
  let lastRequestAt = 0;

  async function rateLimitedFetch(url, options) {
    const wait = Math.max(0, REQUEST_SPACING_MS - (Date.now() - lastRequestAt));
    if (wait > 0) await sleep(wait);
    lastRequestAt = Date.now();

    const response = await fetch(url, options);
    if (response.status === 429) {
      consecutive429 += 1;
      if (consecutive429 >= MAX_CONSECUTIVE_429) {
        throw new HardStopError(`${MAX_CONSECUTIVE_429} consecutive 429s from the Opening Explorer -- stopping (Non-Negotiable 3). Re-run this script to resume from checkpoint.`);
      }
      const retryAfterHeader = response.headers && typeof response.headers.get === 'function' ? Number(response.headers.get('retry-after')) : NaN;
      const waitMs = (Number.isFinite(retryAfterHeader) && retryAfterHeader > 0 ? retryAfterHeader : 5) * 1000;
      console.log(`  429 received (${consecutive429}/${MAX_CONSECUTIVE_429}), honouring Retry-After: waiting ${waitMs}ms`);
      await sleep(waitMs);
      lastRequestAt = Date.now();
      return rateLimitedFetch(url, options);
    }
    consecutive429 = 0;
    return response;
  }

  return rateLimitedFetch;
}

function checkpointPath(band) {
  return path.join(CHECKPOINT_DIR, `${band}.checkpoint.json`);
}

function loadCheckpoint(band) {
  try {
    return JSON.parse(fs.readFileSync(checkpointPath(band), 'utf8'));
  } catch (err) {
    return null;
  }
}

function saveCheckpoint(band, state) {
  fs.mkdirSync(CHECKPOINT_DIR, { recursive: true });
  fs.writeFileSync(checkpointPath(band), JSON.stringify(state), 'utf8');
}

function newCrawlState() {
  return {
    frontier: [{ play: [], reach: 1.0 }],
    visitedPosKeys: {}, // posKey -> true, prevents re-expanding a transposition
    entries: [], // [{ posKey, play, record }], one per EXPANDED (stored) position
    prunedByReach: {}, // ply -> count, for the coverage-depth report (see R2 note below)
    requestCount: 0,
    done: false,
  };
}

/**
 * @param {string} band a RATING_BANDS key.
 * @param {{budget:number, fetchImpl:Function}} opts
 * @returns {Promise<object>} the final crawl state (entries + stats).
 */
async function crawlBand(band, { budget, fetchImpl }) {
  const ratings = RATING_BANDS[band];
  const state = loadCheckpoint(band) || newCrawlState();
  if (state.entries.length > 0 || state.frontier.length !== 1) {
    console.log(`  resuming ${band} from checkpoint: ${state.entries.length} position(s) already expanded, ${state.frontier.length} in frontier, ${state.requestCount} request(s) already made`);
  }

  while (!state.done && state.entries.length < budget) {
    if (state.frontier.length === 0) {
      state.done = true;
      break;
    }
    // Pop the highest-reach frontier entry (linear scan -- frontier size
    // stays in the low thousands at these budgets, so this is negligible
    // next to the ~1s per request this loop is dominated by).
    let bestIdx = 0;
    for (let i = 1; i < state.frontier.length; i += 1) {
      if (state.frontier[i].reach > state.frontier[bestIdx].reach) bestIdx = i;
    }
    const node = state.frontier.splice(bestIdx, 1)[0];
    const ply = node.play.length;

    if (node.reach < MIN_REACH || ply > MAX_PLY) {
      state.prunedByReach[ply] = (state.prunedByReach[ply] || 0) + 1;
      continue;
    }

    const { posKey } = posKeyFor(node.play);
    if (state.visitedPosKeys[posKey]) continue; // transposition already expanded

    let response;
    try {
      response = await fetchMoves({ play: node.play, band, ratings, speeds: SPEEDS, pool: POOL, moves: MOVES_PER_REQUEST, fetchImpl });
    } catch (err) {
      if (err instanceof HardStopError) {
        console.error(`  ${err.message}`);
        saveCheckpoint(band, state);
        return { state, hardStopped: true };
      }
      // A non-429 transport error (timeout, DNS, etc.) -- log and skip this
      // node rather than aborting the whole run; it stays unvisited so a
      // re-run can pick it back up (it's still in nobody's visited set).
      console.error(`  fetch error at ply ${ply} (${node.play.join(',')}): ${err.message} -- skipping this node`);
      continue;
    }
    state.requestCount += 1;

    const total = (response.white || 0) + (response.draws || 0) + (response.black || 0);
    state.visitedPosKeys[posKey] = true;

    if (total < MIN_GAMES) {
      state.prunedByReach[ply] = (state.prunedByReach[ply] || 0) + 1;
      continue; // below the games floor: store nothing, expand nothing further
    }

    state.entries.push({ posKey, play: node.play, record: positionRecordFrom(response) });

    for (const move of response.moves || []) {
      const moveGames = (move.white || 0) + (move.draws || 0) + (move.black || 0);
      if (total === 0 || moveGames === 0) continue;
      const childReach = node.reach * (moveGames / total);
      if (childReach < MIN_REACH || ply + 1 > MAX_PLY) continue;
      state.frontier.push({ play: [...node.play, move.uci], reach: childReach });
    }

    if (state.requestCount % CHECKPOINT_SAVE_EVERY === 0) {
      saveCheckpoint(band, state);
      console.log(`  ${band}: ${state.entries.length}/${budget} positions, ${state.requestCount} request(s), frontier ${state.frontier.length}`);
    }
  }

  saveCheckpoint(band, state);
  return { state, hardStopped: false };
}

/**
 * Groups a band's expanded entries into shard files (spec 2.1: sharded on
 * the first two plies of the path, "root" for ply 0-2), writes them to
 * data/rep/<band>/<shardKey>.json (see OUT_DIR's own header note for why
 * this is a committed source directory, not dist/ directly), and returns
 * per-shard byte sizes for the manifest + budget check.
 */
function writeShardsForBand(band, entries, retrievedDate) {
  const byShardKey = new Map();
  for (const { posKey, play, record } of entries) {
    const key = shardKeyFor(play);
    if (!byShardKey.has(key)) byShardKey.set(key, {});
    byShardKey.get(key)[posKey] = record;
  }

  const bandDir = path.join(OUT_DIR, band);
  fs.mkdirSync(bandDir, { recursive: true });

  const shardFiles = [];
  let bandBytes = 0;
  for (const [shardKey, positions] of byShardKey.entries()) {
    const shard = buildShard({ band, pool: POOL, retrieved: retrievedDate, source: SOURCE_EXPLORER, minGames: MIN_GAMES, positions });
    const json = JSON.stringify(shard);
    const bytes = Buffer.byteLength(json, 'utf8');
    fs.writeFileSync(path.join(bandDir, `${shardKey}.json`), json, 'utf8');
    shardFiles.push({ file: `${band}/${shardKey}.json`, shardKey, positions: Object.keys(positions).length, bytes });
    bandBytes += bytes;
  }

  return { shardFiles, bandBytes };
}

function assertBudgets(bandResults, strict) {
  const problems = [];
  for (const { band, shardFiles, bandBytes } of bandResults) {
    for (const s of shardFiles) {
      if (s.bytes > MAX_SHARD_BYTES) {
        problems.push(`${s.file}: ${s.bytes} bytes exceeds the ${MAX_SHARD_BYTES}-byte (120 KB) per-shard budget`);
      }
    }
    if (bandBytes > MAX_BAND_DIR_BYTES) {
      problems.push(`${band}/: ${bandBytes} bytes exceeds the ${MAX_BAND_DIR_BYTES}-byte (6 MB) per-band-directory budget`);
    }
  }
  if (problems.length > 0) {
    const message = `Shard size budget exceeded:\n  ${problems.join('\n  ')}`;
    if (strict) throw new Error(message);
    console.warn(`WARN: ${message}`);
  }
}

/**
 * Coverage-depth report (spec risk R2). HONEST LIMITATION, stated here and
 * in the manifest: this measures the ply at which THIS CRAWL's own reach
 * threshold started pruning nodes -- a real measurement against 50 actual
 * club-player games (as R2 asks for) needs a Lichess games sample, which is
 * W2's (Personal Opening Report) own fetch, not something this run-by-hand
 * crawler script does. This proxy is still real signal (it directly shows
 * where the crawl itself ran out of budget/reach), just not the exact
 * "median ply where a sample of real games leaves the crawled tree" R2
 * describes -- do not conflate the two when tuning MIN_REACH/MIN_GAMES/MAX_PLY.
 */
function coverageDepthReport(prunedByReach) {
  const plies = Object.keys(prunedByReach).map(Number).sort((a, b) => a - b);
  if (plies.length === 0) return 'no pruning occurred (crawl ended on budget, not on reach/games/ply exhaustion)';
  const totalPruned = plies.reduce((sum, p) => sum + prunedByReach[p], 0);
  let cumulative = 0;
  let medianPly = plies[0];
  for (const p of plies) {
    cumulative += prunedByReach[p];
    if (cumulative >= totalPruned / 2) {
      medianPly = p;
      break;
    }
  }
  return `median prune ply ${medianPly} (${totalPruned} total pruned nodes across plies ${plies[0]}-${plies[plies.length - 1]})`;
}

async function main() {
  const args = process.argv.slice(2);
  let bands = Object.keys(RATING_BANDS);
  let budget = DEFAULT_BUDGET_PER_BAND;
  let useCache = true;
  let strictBudget = false;
  for (let i = 0; i < args.length; i += 1) {
    if (args[i] === '--band') {
      const b = args[++i];
      if (!RATING_BANDS[b]) throw new Error(`--band ${b} is not a recognized band (${Object.keys(RATING_BANDS).join(', ')})`);
      bands = [b];
    } else if (args[i] === '--budget') {
      budget = Number(args[++i]);
    } else if (args[i] === '--no-cache') {
      useCache = false;
    } else if (args[i] === '--strict-budget') {
      strictBudget = true;
    }
  }

  const fetchImpl = withExplorerCache(createRateLimitedFetch(), { enabled: useCache });
  const retrievedDate = new Date().toISOString().slice(0, 10);
  const bandResults = [];
  let anyHardStopped = false;

  for (const band of bands) {
    console.log(`\n=== ${band} (budget ${budget}) ===`);
    const { state, hardStopped } = await crawlBand(band, { budget, fetchImpl });
    if (hardStopped) anyHardStopped = true;
    console.log(`  ${band}: crawl ${hardStopped ? 'STOPPED (rate limited)' : 'finished'} -- ${state.entries.length} position(s), ${state.requestCount} request(s) this run, ${coverageDepthReport(state.prunedByReach)}`);

    const { shardFiles, bandBytes } = writeShardsForBand(band, state.entries, retrievedDate);
    bandResults.push({ band, positions: state.entries.length, requestCount: state.requestCount, shardFiles, bandBytes });
  }

  assertBudgets(bandResults, strictBudget);

  const manifest = {
    v: 1,
    generatedAt: new Date().toISOString(),
    retrieved: retrievedDate,
    pool: POOL,
    source: SOURCE_EXPLORER,
    thresholds: { minReach: MIN_REACH, minGames: MIN_GAMES, maxPly: MAX_PLY, budgetPerBand: budget },
    bands: bandResults.map(({ band, positions, bandBytes, shardFiles }) => ({
      band,
      positions,
      bytes: bandBytes,
      shards: shardFiles.map(({ file, shardKey, positions: p, bytes }) => ({ file, shardKey, positions: p, bytes })),
    })),
  };
  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(path.join(OUT_DIR, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf8');

  console.log('\n=== summary ===');
  for (const r of bandResults) {
    console.log(`  ${r.band}: ${r.positions} positions, ${(r.bandBytes / 1024).toFixed(1)} KB, ${r.shardFiles.length} shard file(s)`);
  }
  console.log(`Wrote ${path.join(OUT_DIR, 'manifest.json')}`);
  if (anyHardStopped) {
    console.log('\nOne or more bands stopped early on rate limiting. Re-run this script (same or no --band flag) to resume from checkpoint.');
    process.exitCode = 1;
  }
}

if (require.main === module) {
  main().catch((err) => {
    console.error('buildBandShards failed:', err.message);
    process.exitCode = 1;
  });
}

module.exports = {
  MIN_REACH,
  MIN_GAMES,
  MAX_PLY,
  DEFAULT_BUDGET_PER_BAND,
  MAX_SHARD_BYTES,
  MAX_BAND_DIR_BYTES,
  POOL,
  SPEEDS,
  createRateLimitedFetch,
  HardStopError,
  crawlBand,
  writeShardsForBand,
  assertBudgets,
  coverageDepthReport,
  newCrawlState,
};
