'use strict';

/**
 * Full static-site build for GitHub Pages staging (local-only: this script
 * does not touch git, GitHub, or any account -- it only writes files under
 * dist/). Produces a self-contained dist/ directory that works when opened
 * directly in a browser via a file:// URL, no server required, since
 * GitHub Pages itself just serves static files.
 *
 * Two features, two different strategies:
 *
 * - Rating-band repertoire explorer: pre-rendered at build time into 8
 *   static HTML files (one per RATING_BANDS key x color), reusing
 *   buildRepertoireTree() + renderRepertoirePage() unchanged. This is the
 *   ONLY place the Lichess API token (LICHESS_API_TOKEN / .lichess-token,
 *   read by fetchOpeningExplorer.js) is used -- it is read locally during
 *   this build step to call the Explorer API, and the resulting HTML files
 *   contain only the aggregated stats the API returned, never the token
 *   itself. assertNoTokenLeak() below checks every file written to dist/
 *   for the literal token string as a build-time safety net, and
 *   test/buildStatic.test.js exercises the same check against a fake token.
 *
 * - Player lookup: a static HTML shell (player.html) plus a plain-JS bundle
 *   (player-lookup.js) assembled by concatenating the existing
 *   fetchLichess.js, process.js, and render.js source (their pure functions
 *   are reused as-is; only the trailing `module.exports` line is stripped
 *   since the browser has no CommonJS module object) with a small DOM
 *   controller (src/browser/playerLookup.client.js). That bundle calls
 *   Lichess's already-public, keyless general API directly from the
 *   visitor's browser -- no token is read, embedded, or needed for this
 *   page at all.
 *
 * Usage: node src/buildStatic.js
 */

const fs = require('fs');
const path = require('path');
const { buildRepertoireTree } = require('./buildRepertoire');
const { RATING_BANDS } = require('./processRepertoire');
const { renderRepertoirePage, escapeHtml } = require('./render');
const { getApiToken } = require('./fetchOpeningExplorer');

// Pre-rendering all 8 band/color combinations issues many sequential
// Explorer API requests (each combination expands several plies), which can
// trip Lichess's rate limiter well before the whole batch finishes. This
// wrapper is ONLY used as the default (real) fetch implementation -- any
// caller that passes its own `fetchImpl` (as every test in
// test/buildStatic.test.js does) bypasses it entirely, so it never adds
// delays or retries to the test suite.
async function politeFetch(url, options) {
  const MAX_ATTEMPTS = 6;
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt += 1) {
    const response = await fetch(url, options);
    if (response.status !== 429 || attempt === MAX_ATTEMPTS) {
      return response;
    }
    const retryAfterHeader = response.headers && typeof response.headers.get === 'function'
      ? Number(response.headers.get('retry-after'))
      : NaN;
    const waitMs = (Number.isFinite(retryAfterHeader) && retryAfterHeader > 0 ? retryAfterHeader : 5) * 1000;
    await new Promise((resolve) => setTimeout(resolve, waitMs));
  }
  // Unreachable, but keeps control flow explicit.
  return fetch(url, options);
}

const OUT_DIR = path.join(__dirname, '..', 'dist');
const COLORS = ['white', 'black'];

const BROWSER_BUNDLE_SOURCES = [
  path.join(__dirname, 'fetchLichess.js'),
  path.join(__dirname, 'process.js'),
  path.join(__dirname, 'render.js'),
];
const BROWSER_CONTROLLER = path.join(__dirname, 'browser', 'playerLookup.client.js');

function repertoireFileName(band, color) {
  const safeBand = band.replace(/[^\w-]/g, '');
  return `repertoire-${safeBand}-${color}.html`;
}

/**
 * Strips the trailing `module.exports = {...};` block from a CommonJS
 * source file so it can be concatenated into a plain <script> for the
 * browser (which has no `module` global). Throws if no such block is found,
 * so a future edit to one of these source files that changes the
 * module.exports shape fails the build loudly instead of silently shipping
 * a stale or broken bundle.
 */
function bundleBrowserModule(srcPath) {
  const src = fs.readFileSync(srcPath, 'utf8');
  const stripped = src.replace(/\n*module\.exports\s*=\s*\{[\s\S]*?\};?\s*$/, '\n');
  if (stripped === src) {
    throw new Error(`bundleBrowserModule: no trailing module.exports block found in ${srcPath}`);
  }
  return stripped;
}

function buildPlayerLookupBundle() {
  const header = [
    '/* Auto-generated by src/buildStatic.js from src/fetchLichess.js, src/process.js,',
    ' * src/render.js, and src/browser/playerLookup.client.js. Do not edit this file',
    ' * directly -- edit the source files above and re-run `node src/buildStatic.js`.',
    ' *',
    ' * This calls only Lichess\'s keyless public API (https://lichess.org/api)',
    ' * directly from your browser. No Lichess API token is used, read, or present',
    ' * anywhere in this file. */',
    '',
  ].join('\n');

  const modules = BROWSER_BUNDLE_SOURCES.map(bundleBrowserModule);
  const controller = fs.readFileSync(BROWSER_CONTROLLER, 'utf8');
  return [header, ...modules, controller].join('\n\n');
}

function indexPage(repertoireLinks) {
  const items = repertoireLinks
    .map(({ band, color, file }) => `<li><a href="${escapeHtml(file)}">${escapeHtml(band)}, ${escapeHtml(color)}</a></li>`)
    .join('\n        ');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Lichess stats POC (static build)</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 700px; margin: 2rem auto; padding: 0 1rem; color: #222; }
    li { margin: 0.3rem 0; }
    footer { color: #999; font-size: 0.8rem; margin-top: 3rem; }
  </style>
</head>
<body>
  <h1>Lichess stats proof of concept (static build)</h1>
  <p>This is a fully static version of the app: every page here is a plain file, no
     server required. It's the version intended for eventual GitHub Pages hosting
     (publishing itself is a separate, not-yet-taken step).</p>

  <h2>Player lookup</h2>
  <p><a href="player.html">Look up any Lichess username &rarr;</a> (fetches live data
     directly in your browser when you open this page; nothing is pre-baked).</p>

  <h2>Rating-band opening-repertoire explorer</h2>
  <p>Pre-rendered at build time for these 8 rating-band / color combinations:</p>
  <ul>
        ${items}
  </ul>

  <footer>Data source: <a href="https://lichess.org/api">lichess.org/api</a>. Generated locally; not deployed or published. See TESTING.md.</footer>
</body>
</html>
`;
}

function playerLookupPage() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Player lookup - Lichess stats POC (static build)</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 760px; margin: 2rem auto; padding: 0 1rem; color: #222; }
    nav { margin-bottom: 1.5rem; }
    nav a { margin-right: 1rem; }
    table { border-collapse: collapse; width: 100%; margin: 1rem 0 2rem; }
    th, td { text-align: left; padding: 0.4rem 0.6rem; border-bottom: 1px solid #ddd; }
    th { background: #f5f5f5; }
    tr.result-win { background: #eafaf0; }
    tr.result-loss { background: #fdecec; }
    tr.result-draw { background: #fafafa; }
    .error { color: #a33; }
    footer { color: #999; font-size: 0.8rem; margin-top: 3rem; }
  </style>
</head>
<body>
  <nav><a href="index.html">Home</a></nav>
  <h1>Player lookup</h1>
  <p>Enter a Lichess username to view rating history and recent games. This runs
     entirely in your browser, calling Lichess's public API directly -- no token
     needed and none is used.</p>
  <form id="lookup-form">
    <input id="username" name="username" placeholder="e.g. DrNykterstein" required>
    <button type="submit">View</button>
  </form>
  <div id="result"></div>
  <footer>Data source: <a href="https://lichess.org/api">lichess.org/api</a>, called directly from this page. Generated locally; not deployed or published.</footer>
  <script src="player-lookup.js"></script>
</body>
</html>
`;
}

async function buildRepertoirePages({ fetchImpl = politeFetch } = {}) {
  const written = [];
  for (const band of Object.keys(RATING_BANDS)) {
    for (const color of COLORS) {
      const data = await buildRepertoireTree({ ratingBand: band, color, fetchImpl });
      const html = renderRepertoirePage({
        ...data,
        nav: { player: 'player.html', repertoire: 'index.html' },
      });
      const file = repertoireFileName(band, color);
      fs.writeFileSync(path.join(OUT_DIR, file), html, 'utf8');
      written.push({ band, color, file });
    }
  }
  return written;
}

/**
 * Reads back every non-directory file just written to outDir and fails loudly
 * if the literal token string appears anywhere in it. This is the explicit,
 * automated check the task calls for, run both here (real build) and by
 * test/buildStatic.test.js (fake token, fake fetch, no live calls).
 */
function assertNoTokenLeak(outDir, token) {
  if (!token) return;
  const offenders = [];
  for (const file of fs.readdirSync(outDir)) {
    const full = path.join(outDir, file);
    if (fs.statSync(full).isDirectory()) continue;
    const content = fs.readFileSync(full, 'utf8');
    if (content.includes(token)) {
      offenders.push(file);
    }
  }
  if (offenders.length > 0) {
    throw new Error(`Lichess API token leaked into generated static output: ${offenders.join(', ')}`);
  }
}

async function buildStatic({ fetchImpl = politeFetch } = {}) {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const repertoireLinks = await buildRepertoirePages({ fetchImpl });
  fs.writeFileSync(path.join(OUT_DIR, 'index.html'), indexPage(repertoireLinks), 'utf8');
  fs.writeFileSync(path.join(OUT_DIR, 'player.html'), playerLookupPage(), 'utf8');
  fs.writeFileSync(path.join(OUT_DIR, 'player-lookup.js'), buildPlayerLookupBundle(), 'utf8');

  assertNoTokenLeak(OUT_DIR, getApiToken());

  return { outDir: OUT_DIR, repertoireLinks };
}

async function main() {
  try {
    const { outDir, repertoireLinks } = await buildStatic();
    console.log(`Wrote static site to ${outDir}`);
    console.log(`  - index.html (links to player lookup + ${repertoireLinks.length} repertoire pages)`);
    console.log('  - player.html + player-lookup.js (client-side player lookup, no token used)');
    for (const { file } of repertoireLinks) {
      console.log(`  - ${file}`);
    }
    console.log('Verified: no Lichess API token string appears in any generated file.');
    console.log('Open dist/index.html directly in a browser (file:// URL) -- no server needed.');
  } catch (err) {
    console.error('Static build failed:', err.message);
    process.exitCode = 1;
  }
}

if (require.main === module) {
  main();
}

module.exports = {
  buildStatic,
  buildRepertoirePages,
  buildPlayerLookupBundle,
  bundleBrowserModule,
  indexPage,
  playerLookupPage,
  repertoireFileName,
  assertNoTokenLeak,
};
